### ISSUE TITLE
Clist_modern: crash at "clcitems.cpp (683): Clist_SaveStateAndRebuildList"  and  "modern_clc.cpp (658): clcOnTimer"

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#2406] opened 2020-05-16 20:41 UTC
CrashLog: http://coraksoft1.narod.ru/temp/miranda/Miranda_crash_20200510_Clist_SaveStateAndRebuildList.7z

Likely cause of the crash plugin: Miranda NG

Exception: Access Violation at address 1279D7CF. Reading from address 00000000.

Stack Trace:
---------------------------------------------------------------
1279D7CF (mir_app 12780000): w:\miranda-build\src\mir_app\src\clcitems.cpp (683): Clist_SaveStateAndRebuildList
1279A867 (mir_app 12780000): w:\miranda-build\src\mir_app\src\clc.cpp (874): fnContactListControlWndProc
163D06DA (Clist_modern 163C0000): w:\miranda-build\plugins\clist_modern\src\modern_clc.cpp (658): clcOnTimer
163D1B36 (Clist_modern 163C0000): w:\miranda-build\plugins\clist_modern\src\modern_clc.cpp (1742): cli_ContactListControlWndProc
163D19A6 (Clist_modern 163C0000): w:\miranda-build\plugins\clist_modern\src\modern_clc.cpp (1713): cli_ContactListControlWndProc
0012E5CC ((module-name not available) 00000000): (filename not available) (0): (function-name not available)

**Comment by georgehazan** [comment] 2020-05-17 17:12
та же фигня... половина плагинов от 4 мая, половина - от 9-го...
duplicate of #2404

**Closed by georgehazan** 2020-05-17 17:12 UTC
Labels: bug
