### ISSUE TITLE
tox крашится при подключении

### ISSUE THREAD

**Issue by Mataes** [miranda-ng/miranda-ng#1794] opened 2019-01-24 06:25 UTC
>	Tox.dll!do_tcp_conns(TCP_Connections * tcp_c=0x00000000, void * userdata=0x07fcfdc4) Line 1420	C	Symbols loaded.
 	Tox.dll!do_tcp_connections(TCP_Connections * tcp_c=0x00000000, void * userdata) Line 1506	C	Symbols loaded.
 	Tox.dll!do_tcp(Net_Crypto * c=0x17f1a558, void * userdata=0x07fcfdc4) Line 2251	C	Symbols loaded.
 	Tox.dll!do_net_crypto(Net_Crypto * c=0x17f1a558, void * userdata=0x07fcfdc4) Line 3041	C	Symbols loaded.
 	Tox.dll!do_messenger(Messenger * m=0x17f80ba0, void * userdata=0x07fcfdc4) Line 2623	C	Symbols loaded.
 	Tox.dll!tox_iterate(Tox * tox=0x09e52550, void * user_data=0x005c7790) Line 748	C	Symbols loaded.
 	Tox.dll!CToxProto::OnToxPoll(void * arg=0x005c7790, unsigned char __formal='\x1') Line 84	C++	Symbols loaded.
 	ntdll.dll!_RtlpTpTimerCallback@12()	Unknown	Non-user code. Symbols loaded.
 	ntdll.dll!_TppTimerpExecuteCallback@8()	Unknown	Non-user code. Symbols loaded.
 	ntdll.dll!_TppWorkerThread@4()	Unknown	Non-user code. Symbols loaded.
 	kernel32.dll!@BaseThreadInitThunk@12()	Unknown	Non-user code. Symbols loaded.
 	ntdll.dll!___RtlUserThreadStart@8()	Unknown	Non-user code. Symbols loaded.
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown	Non-user code. Symbols loaded.

**Comment by georgehazan** [comment] 2019-02-26 18:57
duplicate of #1852, already fixed

**Closed by georgehazan** 2019-02-26 18:57 UTC
Labels: Tox, blocker, bug, crash
