### ISSUE TITLE
YAMN: Crash on opening mail. on "pop3.cpp (300): CPop3Client::Top"

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#489] opened 2016-10-22 14:26 UTC
**Reported by Corak on 30 Dec 2015 07:42 UTC**
   "0x15b27ff2 (YAMN.dll)"  "Miranda32.exe": 0xC0000005:      "0xdddddde1".

>   YAMN.dll!CPop3Client::Top(int nr, int lines)   300 + 0x9    C++
>     YAMN.dll!SynchroPOP3(CheckParam \* WhichTemp)   718 + 0x11   C++
>     kernel32.dll!_BaseThreadStart@8()  + 0x37   
> ---
> 
> Likely cause of the crash plugin: Mail Notifier

Exception: Access Violation at address 15B27FF2. Reading from address DDDDDDE1.
## Stack Trace:

15B27FF2 (YAMN 15B10000): d:\soft\network\im\miranda\src\trunk\plugins\yamn\src\proto\pop3\pop3.cpp (300): CPop3Client::Top
15B29E74 (YAMN 15B10000): d:\soft\network\im\miranda\src\trunk\plugins\yamn\src\proto\pop3\pop3comm.cpp (718): SynchroPOP3
7C80B729 (kernel32 7C800000): (filename not available) (0): GetModuleFileNameA

**Comment by dartraiden** [comment] 2016-12-13 20:34
Duplicate of #438

**Closed by dartraiden** 2016-12-13 20:34 UTC
Labels: another plugin, bug, major
