### ISSUE TITLE
Miranda crashed when IRC awaits for new nickname

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#138] opened 2016-10-17 16:39 UTC
**Reported by kxepal on 14 Oct 2012 21:19 UTC**
Miranda crashed when IRC prompts for new room nickname, but didn't get response for a long time.

Steps to reproduce:
1. You have dynamic IP that get changed periodically;
2. Join to some IRC room with nickname Foo;
3. Wait when ISP change your IP address;
4. Rejoin to the same room;
5. You will be asked to setup another nickname since there is another person with the same. Actually it's you, old you, but IRC server will kick this guy after ping timeout (4-5 mins);
6. Don't set new nickname, don't do anything, go grab some tea, talk with friends, look out the window. After 5-10 minutes you'll get crash log.

**Comment by georgehazan** [comment] 2016-10-17 16:39
**Modified by wishmaster on 14 May 2014 07:32 UTC**

**Comment by dartraiden** [comment] 2016-12-11 20:23
Duplicate of #107

**Closed by dartraiden** 2016-12-11 20:23 UTC
Labels: bug, IRC, major
