### ISSUE TITLE
Need a button/command to collapse/uncollapse all the groups in contact list

### ISSUE THREAD

**Issue by evle-zzz** [miranda-ng/miranda-ng#1914] opened 2019-04-04 04:55 UTC
**Is your feature request related to a problem? Please describe.**
We have a huge contact list (3000+ users) divided by nested groups corresponding to organizations structure. Use wants to write somebody whose name he doesn't know but he knows his group. There is no easy way to filter such users.

**Describe the solution you'd like**
It would be good to be able to collapse all the groups and then manually unfold a branch required.

**Describe alternatives you've considered**
Maybe hiding unmatched groups while filtering in contact list would help too but it looks less universal.

**Comment by dartraiden** [comment] 2019-04-04 10:13
Duplicate of #1908

**Closed by dartraiden** 2019-04-04 10:13 UTC
Labels: enhancement
