### ISSUE TITLE
IRC: Twitch.tv and 'improperly formatted auth'

### ISSUE THREAD

**Issue by Tharn** [miranda-ng/miranda-ng#1082] opened 2017-12-29 18:52 UTC
### Expected behavior
When using IRC with Twitch and an oauth:xxx.. in the password field, IRC should be able to connect to the Twitch network.

### Actual behavior
Server window shows 'improperly formatted auth', hinting that the data sent to the server is somehow malformed.

### Does it work in stable version?
Yes. This broke just recently.

### Steps to reproduce that behavior
0.95.8 19063

https://dev.twitch.tv/docs/irc

**Comment by dartraiden** [comment] 2017-12-29 19:02
We need IRCv3 support for this. So it's duplicate of #719

**Comment by Tharn** [comment] 2017-12-30 06:45
Actually, we don't. 0.95.7 stable works perfectly fine with the old IRC client. A recent change introduced a regression in IRC auth.

I think IRCv3 is a separate issue.

**Comment by georgehazan** [comment] 2017-12-30 15:59
check if you occasionally turned on SASL auth

**Comment by Tharn** [comment] 2017-12-30 17:06
SASL auth is a very recent addition too isn't it? Remember seeing an issue about it just the other day.

I just compared the same settings, loading nightly and 0.95.7 and finding that the former does not work, but the latter works. Something must have changed.

**Comment by georgehazan** [comment] 2018-01-03 11:02
yes, but this change is present in the nightly builds :)
frankly speaking, if the SASL button is unchecked for this account, the behaviour should be strictly the same as in the old versions... would you please attach a network log? there should be no CAPS in it

**Comment by Tharn** [comment] 2018-01-04 07:56
0.95.8 nightly, not working

```
[08:45:24 0734] [IRC_1] Connection request to irc.chat.twitch.tv:6667 (Flags 0)....
[08:45:24 0734] [IRC_1] (00000000053364D0) Connecting to server irc.chat.twitch.tv:6667....
[08:45:24 0734] [IRC_1] (00000000053364D0) Connecting to ip 52.34.236.73:6667 ....
[08:45:25 0734] [IRC_1] (764) Connected to irc.chat.twitch.tv:6667
[08:45:25 0734] [IRC_1] (00000000053364D0:764) Data sent
NICK shiznaggles
[08:45:25 0734] [IRC_1] (00000000053364D0:764) Data sent
USER shiz ALTAIR server :shiz
[08:45:25 0734] [IRC_1] (00000000053364D0:764) Data sent
PASS oauth:myoauthtokengoeshere
[08:45:25 06BC] [IRC_1] (00000000053364D0:764) Data received
:tmi.twitch.tv NOTICE * :Improperly formatted auth
[08:45:35 06BC] [IRC_1] (00000000053364D0:764) Connection closed internal
[08:45:35 06BC] [IRC_1] (00000000053364D0:4294967295) Connection closed
```

0.95.7 stable, working

```
[08:50:47 00F8] [IRC_1] Connection request to irc.chat.twitch.tv:6667 (Flags 0)....
[08:50:47 00F8] [IRC_1] (0000000000205940) Connecting to server irc.chat.twitch.tv:6667....
[08:50:47 00F8] [IRC_1] (0000000000205940) Connecting to ip 35.165.71.218:6667 ....
[08:50:47 00F8] [IRC_1] (568) Connected to irc.chat.twitch.tv:6667
[08:50:48 00F8] [IRC_1] (0000000000205940:568) Data sent
PASS oauth:myoauthtokengoeshere
[08:50:48 00F8] [IRC_1] (0000000000205940:568) Data sent
NICK shiznaggles
[08:50:48 00F8] [IRC_1] (0000000000205940:568) Data sent
USER shiz ALTAIR server :shiz
[08:50:48 0870] [IRC_1] (0000000000205940:568) Data received
:tmi.twitch.tv 001 shiznaggles :Welcome, GLHF!
:tmi.twitch.tv 002 shiznaggles :Your host is tmi.twitch.tv
:tmi.twitch.tv 003 shiznaggles :This server is rather new
:tmi.twitch.tv 004 shiznaggles :-
:tmi.twitch.tv 375 shiznaggles :-
:tmi.twitch.tv 372 shiznaggles :You are in a maze of twisty passages, all alike.
:tmi.twitch.tv 376 shiznaggles :>
```

Does this suffice, or do you need the whole thing?

**Comment by Tharn** [comment] 2018-01-04 15:59
Oh, one difference seems to be the order in which PASS, NICK and USER are sent.

**Comment by georgehazan** [comment] 2018-01-09 16:06
yes, let's try to fix it

**Closed** 2018-01-09 16:08 UTC
Labels: IRC, bug, regression
