### ISSUE TITLE
Tox: libtox crash on reconnection on "group.c: do_groupchats"

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#457] opened 2016-10-21 20:01 UTC
**Reported by Corak on 21 Sep 2015 01:16 UTC**

```
Exception: Access Violation at address 13DBE2C0. Reading from address 0000000C.

Stack Trace:
---------------------------------------------------------------
13DBE2C0 (libtox 13DA0000): ..\toxcore\group.c (2245): do_groupchats

```

**Comment by dartraiden** [comment] 2016-12-13 15:59
Duplicate of #442

**Closed by dartraiden** 2016-12-13 15:59 UTC
Labels: bug, major, Tox
