### ISSUE TITLE
Jabber contacts goes offline on unanswered startup dialogs

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#139] opened 2016-10-17 16:39 UTC
**Reported by kxepal on 14 Oct 2012 21:29 UTC**
Steps to reproduce:
1. Make sure that on startup Miranda sets Online status for Jabber protocols;
2. Break YAMN database or forget to setup path to PGP or do something that will raise some diablog, messagebox or something before protocols get event to set status;
3. Wait for a minute, close dialog;
4. Jabber protocols will have online status, but all contacts are actually offline.
5. Swapping protocol status online -> offline -> online doesn't make a sense - you'll have to chat with offline contacts, be in offline MUC's.
6. Current fix is force start up protocol status to be offline and restart Miranda.

Could be reproduced on any build up to #1722. Original Miranda of 0.10 version also affected to this bug.

**Comment by georgehazan** [comment] 2016-10-17 16:39
**Modified by wishmaster on 3 Jan 2013 09:53 UTC**

**Comment by georgehazan** [comment] 2016-10-17 16:39
**Modified by watcher on 1 Jan 2014 16:52 UTC**

**Comment by georgehazan** [comment] 2016-10-17 16:39
**Modified by watcher on 29 Jun 2014 11:32 UTC**

**Comment by dartraiden** [comment] 2016-12-11 20:23
Duplicate of #108

**Closed by dartraiden** 2016-12-11 20:23 UTC
Labels: bug, Jabber, major
