### ISSUE TITLE
LeftClientMargin

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#581] opened 2016-10-22 18:35 UTC
**Reported by Dvorak Stepan on 31 Jul 2016 12:28 UTC**
If LeftClientMargin=b0 ShowDelay not working (ShowDelay is constantly 0).

**Comment by georgehazan** [comment] 2016-10-22 18:35
**Modified by Dvorak.Stepan on 31 Jul 2016 12:30 UTC**

**Comment by tweimer** [comment] 2016-11-19 21:49
Duplicate of #618

**Closed by tweimer** 2016-11-19 21:49 UTC
Labels: bug, C: clist_modern, major
