### ISSUE TITLE
YAMN (Mail Notifier): Crash on opening some mail by "pop3comm.cpp: SynchroPOP3"

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#452] opened 2016-10-21 20:00 UTC
**Reported by Corak on 20 Sep 2015 16:25 UTC**

```
Likely cause of the crash plugin: Mail Notifier

Exception: Access Violation at address 17A06EF3. Reading from address 01680010.

Stack Trace:
---------------------------------------------------------------
17A06EF3 (YAMN 17A00000): e:\sources\miranda_ng_compilation\plugins\yamn\src\proto\pop3\pop3comm.cpp (945): SynchroPOP3
7C80B729 (kernel32 7C800000): (filename not available) (0): GetModuleFileNameA

```

**Comment by dartraiden** [comment] 2016-12-13 15:57
Duplicate of #437

**Closed by dartraiden** 2016-12-13 15:57 UTC
Labels: another plugin, bug, major
