### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by alexeik** [miranda-ng/miranda-ng#1791] opened 2019-01-23 14:29 UTC
Miranda Crash Report from 23 Jan 2019 17:28:22. Crash Dumper v.0.1.0.2

Likely cause of the crash plugin: ICQ-WIM protocol

Exception: Access Violation at address 18207BC4. Reading from address 00000000.

Stack Trace:
---------------------------------------------------------------
18207BC4 (ICQ 18200000): w:\miranda-build\protocols\icq-wim\src\server.cpp (65): CIcqProto::CheckOwnMessage
182082FC (ICQ 18200000): w:\miranda-build\protocols\icq-wim\src\server.cpp (642): CIcqProto::OnSendMessage
182039ED (ICQ 18200000): w:\miranda-build\protocols\icq-wim\src\http.cpp (204): CIcqProto::ExecuteRequest
18203BD3 (ICQ 18200000): w:\miranda-build\protocols\icq-wim\src\http.cpp (52): CIcqProto::ServerThread
1285241C (mir_core 12840000): w:\miranda-build\src\mir_core\src\threads.cpp (161): forkthreadex_r
7729343D (kernel32 77280000): (filename not available) (0): BaseThreadInitThunk
77D49802 (ntdll 77D10000): (filename not available) (0): RtlInitializeExceptionChain
77D497D5 (ntdll 77D10000): (filename not available) (0): RtlInitializeExceptionChain

CPU: AMD FX(tm)-8320 Eight-Core Processor  [AMD64 Family 21 Model 2 Stepping 0] [DEP Enabled] [8 CPUs]
Installed RAM: 15276 MBytes
Microsoft Windows 7 Ultimate Edition, 64-bit Service Pack 1 (build 7601)
Internet Explorer: 9.11.9600.19155 (build 99600)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : English/English | Russian/Russian

Miranda NG Version: 0.95.11 alpha build #21243 (003b1efecb) [running inside WOW64]
Build time: 23 Jan 2019 14:16:36
Profile: C:\ice.ng\Profiles\ngdebug\ngdebug.dat
Language pack: No language pack installed
Service Mode: No

Active Plugins (18):
¤ AVS.dll v.0.95.11.0 [20 Jan 2019 2:00:44] - Avatar service 
¤ Clist_modern.dll v.0.95.11.0 [20 Jan 2019 2:01:08] - Modern contact list 
¤ CrashDumper.dll v.0.95.11.0 [10 Jan 2019 2:01:08] - Crash dumper 
¤ Db_autobackups.dll v.0.95.11.0 [23 Jan 2019 14:16:46] - Db autobackuper 
¤ Dbx_mdbx.dll v.0.95.11.0 [23 Jan 2019 14:17:56] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.0.95.11.0 [23 Jan 2019 14:16:40] - Miranda NG mmap database driver 
¤ Dbx_sqlite.dll v.0.95.11.0 [4 Jan 2019 19:37:12] - Miranda NG SQLite database driver 
¤ Dummy.dll v.0.95.11.0 [23 Jan 2019 14:17:36] - Dummy protocol 
¤ Facebook.dll v.0.95.11.0 [19 Jan 2019 2:01:28] - Facebook 
¤ GmailNotifier.dll v.0.95.11.0 [19 Jan 2019 2:01:56] - Gmail Multiple Notifier 
¤ historypp.dll v.1.5.1.5 [21 Jan 2019 2:02:46] - History++ 
¤ ICQ.dll v.0.95.11.0 [23 Jan 2019 14:17:56] - ICQ-WIM protocol 
¤ Import.dll v.0.95.11.0 [23 Jan 2019 14:16:54] - Import contacts and messages 
¤ Jabber.dll v.0.95.11.0 [19 Jan 2019 2:01:36] - Jabber protocol 
¤ PluginUpdater.dll v.0.95.11.0 [8 Jan 2019 18:34:44] - Plugin updater 
¤ SkypeWeb.dll v.0.95.11.0 [19 Jan 2019 2:02:08] - Skype protocol (Web) 
¤ TabSRMM.dll v.0.95.11.0 [19 Jan 2019 2:01:08] - TabSRMM 
¤ TopToolBar.dll v.0.95.11.0 [11 Dec 2018 12:06:30] - TopToolBar 

Loaded Modules:
-------------------------------------------------------------------------------
C:\ice.ng\Miranda32.exe  00400000 - 0040B000 v.0.95.11.0 [23 Jan 2019 14:16:36]
C:\Windows\SysWOW64\ntdll.dll  77D10000 - 77E90000 v.6.1.7601.24260 [30 Oct 2018 23:23:19]
C:\Windows\syswow64\kernel32.dll  77280000 - 77390000 v.6.1.7601.24260 [30 Oct 2018 23:23:19]
C:\Windows\syswow64\KERNELBASE.dll  75B30000 - 75B77000 v.6.1.7601.24260 [30 Oct 2018 23:23:19]
C:\Windows\syswow64\USER32.dll  75870000 - 75970000 v.6.1.7601.23594 [10 Nov 2016 19:19:40]
C:\Windows\syswow64\GDI32.dll  75970000 - 75A00000 v.6.1.7601.24260 [30 Oct 2018 23:23:22]
C:\Windows\syswow64\LPK.dll  75D60000 - 75D6A000 v.6.1.7601.24231 [30 Oct 2018 23:23:22]
C:\Windows\syswow64\USP10.dll  75730000 - 757CD000 v.1.626.7601.23894 [16 Aug 2017 18:10:30]
C:\Windows\syswow64\msvcrt.dll  75C70000 - 75D1C000 v.7.0.7601.17744 [16 Dec 2011 10:52:58]
C:\Windows\syswow64\ADVAPI32.dll  75A80000 - 75B21000 v.6.1.7601.24260 [30 Oct 2018 23:23:21]
C:\Windows\SysWOW64\sechost.dll  75660000 - 75679000 v.6.1.7601.18869 [25 May 2015 21:01:39]
C:\Windows\syswow64\RPCRT4.dll  75B80000 - 75C70000 v.6.1.7601.24260 [30 Oct 2018 23:23:19]
C:\Windows\syswow64\SspiCli.dll  75480000 - 754E0000 v.6.1.7601.24260 [30 Oct 2018 23:23:19]
C:\Windows\syswow64\CRYPTBASE.dll  75470000 - 7547C000 v.6.1.7601.24260 [30 Oct 2018 23:23:19]
C:\Windows\syswow64\SHELL32.dll  765E0000 - 7722C000 v.6.1.7601.24234 [30 Oct 2018 23:23:22]
C:\Windows\syswow64\SHLWAPI.dll  760F0000 - 76147000 v.6.1.7601.17514 [21 Nov 2010 6:23:48]
C:\Windows\system32\IMM32.DLL  77760000 - 777C0000 v.6.1.7601.17514 [21 Nov 2010 6:24:25]
C:\Windows\syswow64\MSCTF.dll  75510000 - 755DD000 v.6.1.7601.23915 [30 Oct 2018 23:23:19]
C:\ice.ng\libs\ucrtbase.dll  69DC0000 - 69EA0000 v.10.0.14393.795 [16 Nov 2018 16:41:54]
C:\ice.ng\api-ms-win-core-timezone-l1-1-0.dll  6ACB0000 - 6ACB3000 v.10.0.10586.15 [25 May 2017 10:39:24]
C:\ice.ng\api-ms-win-core-file-l2-1-0.dll  69460000 - 69463000 v.10.0.10586.15 [25 May 2017 10:39:24]
C:\ice.ng\api-ms-win-core-localization-l1-2-0.dll  69450000 - 69453000 v.10.0.10586.15 [25 May 2017 10:39:24]
C:\ice.ng\api-ms-win-core-synch-l1-2-0.dll  69440000 - 69443000 v.10.0.10586.15 [25 May 2017 10:39:24]
C:\ice.ng\api-ms-win-core-processthreads-l1-1-1.dll  68090000 - 68093000 v.10.0.10586.15 [25 May 2017 10:39:24]
C:\ice.ng\api-ms-win-core-file-l1-2-0.dll  68080000 - 68083000 v.10.0.10586.15 [25 May 2017 10:39:24]
C:\ice.ng\api-ms-win-crt-runtime-l1-1-0.dll  66490000 - 66494000 v.10.0.10586.15 [25 May 2017 10:39:24]
C:\ice.ng\api-ms-win-crt-stdio-l1-1-0.dll  66480000 - 66484000 v.10.0.10586.15 [25 May 2017 10:39:24]
C:\ice.ng\api-ms-win-crt-locale-l1-1-0.dll  66470000 - 66473000 v.10.0.10586.15 [25 May 2017 10:39:24]
C:\ice.ng\api-ms-win-crt-heap-l1-1-0.dll  66460000 - 66463000 v.10.0.10586.15 [25 May 2017 10:39:24]
C:\ice.ng\VCRUNTIME140.dll  66440000 - 66454000 v.14.11.25325.0 [25 May 2017 10:39:24]
C:\ice.ng\api-ms-win-crt-string-l1-1-0.dll  66430000 - 66434000 v.10.0.10586.15 [25 May 2017 10:39:24]
C:\ice.ng\api-ms-win-crt-convert-l1-1-0.dll  66420000 - 66424000 v.10.0.10586.15 [25 May 2017 10:39:24]
C:\ice.ng\libs\mir_app.mir  126A0000 - 1276C000 v.0.95.11.21243 [23 Jan 2019 14:16:34]
C:\Windows\system32\WINMM.dll  74540000 - 74572000 v.6.1.7601.17514 [21 Nov 2010 6:24:16]
C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.18837_none_41e855142bd5705d\COMCTL32.dll  72370000 - 7250E000 v.6.10.7601.18837 [24 Apr 2015 20:54:13]
C:\Windows\syswow64\WS2_32.dll  75D20000 - 75D55000 v.6.1.7601.23451 [11 May 2016 18:19:26]
C:\Windows\syswow64\NSI.dll  777E0000 - 777E6000 v.6.1.7601.23889 [11 Aug 2017 9:19:39]
C:\Windows\system32\UxTheme.dll  70CE0000 - 70D60000 v.6.1.7600.16385 [14 Jul 2009 4:11:24]
C:\Windows\syswow64\COMDLG32.dll  75A00000 - 75A7B000 v.6.1.7601.17514 [21 Nov 2010 6:23:48]
C:\Windows\syswow64\ole32.dll  77390000 - 774ED000 v.6.1.7601.24168 [30 Oct 2018 23:23:19]
C:\ice.ng\libs\FreeImage.mir  12000000 - 12092000 [23 Jan 2019 14:16:28]
C:\ice.ng\libs\zlib.mir  12A80000 - 12A99000 v.1.2.11.0 [23 Jan 2019 14:16:14]
C:\ice.ng\api-ms-win-crt-utility-l1-1-0.dll  66410000 - 66413000 v.10.0.10586.15 [25 May 2017 10:39:24]
C:\ice.ng\api-ms-win-crt-time-l1-1-0.dll  66400000 - 66403000 v.10.0.10586.15 [25 May 2017 10:39:24]
C:\ice.ng\MSVCP140.dll  66390000 - 663FD000 v.14.11.25325.0 [25 May 2017 10:39:24]
C:\ice.ng\api-ms-win-crt-math-l1-1-0.dll  66380000 - 66385000 v.10.0.10586.15 [25 May 2017 10:39:24]
C:\ice.ng\api-ms-win-crt-multibyte-l1-1-0.dll  66370000 - 66375000 v.10.0.10586.15 [25 May 2017 10:39:24]
C:\ice.ng\api-ms-win-crt-filesystem-l1-1-0.dll  66360000 - 66363000 v.10.0.10586.15 [25 May 2017 10:39:24]
C:\ice.ng\api-ms-win-crt-environment-l1-1-0.dll  66350000 - 66353000 v.10.0.10586.15 [25 May 2017 10:39:24]
C:\ice.ng\libs\mir_core.mir  12840000 - 12863000 v.0.95.11.21243 [23 Jan 2019 14:16:16]
C:\Windows\system32\WTSAPI32.dll  72B80000 - 72B8D000 v.6.1.7601.17514 [21 Nov 2010 6:23:54]
C:\Windows\system32\VERSION.dll  72F60000 - 72F69000 v.6.1.7600.16385 [14 Jul 2009 4:16:17]
C:\Windows\system32\Secur32.dll  72B60000 - 72B68000 v.6.1.7601.24260 [30 Oct 2018 23:23:19]
C:\Windows\system32\dwmapi.dll  71F40000 - 71F53000 v.6.1.7601.18917 [9 Jul 2015 20:42:54]
C:\Windows\syswow64\CLBCatQ.DLL  76540000 - 765C3000 v.2001.12.8530.16385 [14 Jul 2009 4:15:03]
C:\Windows\syswow64\OLEAUT32.dll  75680000 - 75711000 v.6.1.7601.24117 [30 Oct 2018 23:23:19]
C:\Windows\system32\explorerframe.dll  661E0000 - 66350000 v.6.1.7601.24234 [30 Oct 2018 23:23:22]
C:\Windows\system32\DUser.dll  661B0000 - 661DF000 v.6.1.7600.16385 [14 Jul 2009 4:15:13]
C:\Windows\system32\DUI70.dll  660F0000 - 661A2000 v.6.1.7600.16385 [14 Jul 2009 4:15:13]
C:\ice.ng\Plugins\CrashDumper.dll  175C0000 - 175D1000 v.0.1.0.2 [10 Jan 2019 2:01:08]
C:\Windows\system32\dbghelp.dll  66000000 - 660EB000 v.6.1.7601.17514 [21 Nov 2010 6:24:09]
C:\ice.ng\Plugins\Dbx_mdbx.dll  177E0000 - 177F2000 v.0.95.9.1 [23 Jan 2019 14:17:56]
C:\ice.ng\libs\libmdbx.mir  125A0000 - 125CB000 [23 Jan 2019 14:17:52]
C:\ice.ng\Plugins\Dbx_mmap.dll  17820000 - 17830000 v.0.95.8.1 [23 Jan 2019 14:16:40]
C:\ice.ng\Plugins\Dbx_sqlite.dll  17840000 - 1784B000 v.0.95.10.2 [4 Jan 2019 19:37:12]
C:\ice.ng\libs\sqlite3.mir  12900000 - 12970000 [23 Jan 2019 14:16:48]
C:\ice.ng\Plugins\Import.dll  18300000 - 18312000 v.0.95.10.1 [23 Jan 2019 14:16:54]
C:\ice.ng\libs\libjson.mir  12580000 - 1258C000 [23 Jan 2019 14:16:40]
C:\ice.ng\Core\stdcrypt.dll  13060000 - 1306C000 v.0.95.11.21243 [23 Jan 2019 14:16:20]
C:\ice.ng\Core\stdssl.dll  13120000 - 13128000 v.0.95.11.21243 [23 Jan 2019 14:16:18]
C:\Windows\syswow64\CRYPT32.dll  77800000 - 77922000 v.6.1.7601.23971 [30 Oct 2018 23:23:19]
C:\Windows\syswow64\MSASN1.dll  75720000 - 7572C000 v.6.1.7601.17514 [21 Nov 2010 6:23:48]
C:\Windows\system32\WSOCK32.dll  71F30000 - 71F37000 v.6.1.7600.16385 [14 Jul 2009 4:16:20]
C:\Windows\system32\Msftedit.dll  664E0000 - 66574000 v.5.41.21.2510 [21 Nov 2010 6:24:14]
C:\ice.ng\Plugins\Clist_modern.dll  172A0000 - 17312000 v.0.9.1.8 [20 Jan 2019 2:01:08]
C:\Windows\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.0.7601.24260_none_6cb7d7730706013f\gdiplus.dll  65E50000 - 65FF8000 v.5.2.7601.24260 [30 Oct 2018 23:23:21]
C:\Windows\system32\MSIMG32.dll  6EEC0000 - 6EEC5000 v.6.1.7601.24234 [30 Oct 2018 23:23:21]
C:\Windows\system32\WindowsCodecs.dll  6EA40000 - 6EB71000 v.6.2.9200.22551 [30 Oct 2018 23:23:24]
C:\ice.ng\Plugins\AVS.dll  170C0000 - 170D1000 v.0.98.1.1 [20 Jan 2019 2:00:44]
C:\ice.ng\Plugins\Db_autobackups.dll  17860000 - 1786E000 v.0.1.0.2 [23 Jan 2019 14:16:46]
C:\ice.ng\Plugins\Dummy.dll  178C0000 - 178C8000 v.0.2.0.0 [23 Jan 2019 14:17:36]
C:\ice.ng\Plugins\Facebook.dll  17920000 - 1795F000 v.0.4.2.1 [19 Jan 2019 2:01:28]
C:\ice.ng\Plugins\GmailNotifier.dll  17CE0000 - 17CEB000 v.1.0.1.2 [19 Jan 2019 2:01:56]
C:\ice.ng\Plugins\historypp.dll  17D00000 - 17EED000 [21 Jan 2019 2:02:46]
C:\Windows\system32\winspool.drv  74600000 - 74651000 v.6.1.7601.17514 [21 Nov 2010 6:24:08]
C:\Windows\system32\RICHED20.DLL  69D40000 - 69DB6000 v.5.31.23.1230 [21 Nov 2010 6:24:28]
C:\ice.ng\Plugins\ICQ.dll  18200000 - 18212000 v.0.95.10.1 [23 Jan 2019 14:17:56]
C:\ice.ng\libs\LIBEAY32.mir  65D00000 - 65E42000 v.1.0.2.18 [21 Nov 2018 14:46:18]
C:\ice.ng\api-ms-win-crt-conio-l1-1-0.dll  6C140000 - 6C143000 v.10.0.10586.15 [25 May 2017 10:39:24]
C:\ice.ng\Plugins\Jabber.dll  02BE0000 - 02C79000 v.0.11.0.5 [19 Jan 2019 2:01:36]
C:\ice.ng\libs\libaxolotl.mir  121E0000 - 1220F000 [19 Jan 2019 2:01:14]
C:\Windows\system32\DNSAPI.dll  6EE30000 - 6EE74000 v.6.1.7601.24168 [30 Oct 2018 23:23:22]
C:\ice.ng\Plugins\PluginUpdater.dll  055E0000 - 055F6000 v.0.2.0.2 [8 Jan 2019 18:34:44]
C:\ice.ng\Plugins\SkypeWeb.dll  05600000 - 0563B000 v.0.12.2.5 [19 Jan 2019 2:02:08]
C:\ice.ng\Plugins\TabSRMM.dll  05900000 - 0597D000 v.3.5.0.12 [19 Jan 2019 2:01:08]
C:\ice.ng\Plugins\TopToolBar.dll  02440000 - 0244E000 v.0.8.0.5 [11 Dec 2018 12:06:30]
C:\ice.ng\Core\stduserinfo.dll  13160000 - 1316D000 v.0.95.11.21243 [23 Jan 2019 14:16:18]
C:\ice.ng\Core\stdemail.dll  13080000 - 13086000 v.0.95.11.21243 [23 Jan 2019 14:16:18]
C:\ice.ng\Core\stdfile.dll  130A0000 - 130B0000 v.0.95.11.21243 [23 Jan 2019 14:16:20]
C:\ice.ng\Core\stdautoaway.dll  13000000 - 13008000 v.0.95.11.21243 [23 Jan 2019 14:16:20]
C:\ice.ng\Core\stduseronline.dll  13180000 - 13187000 v.0.95.11.21243 [23 Jan 2019 14:16:18]
C:\ice.ng\Core\stdaway.dll  13020000 - 13029000 v.0.95.11.21243 [23 Jan 2019 14:16:18]
C:\Windows\system32\mswsock.dll  6D2A0000 - 6D2DC000 v.6.1.7601.23451 [11 May 2016 18:19:16]
C:\Windows\System32\wshtcpip.dll  6EDD0000 - 6EDD5000 v.6.1.7600.16385 [14 Jul 2009 4:16:20]
C:\Windows\System32\wship6.dll  6D290000 - 6D296000 v.6.1.7600.16385 [14 Jul 2009 4:16:20]
C:\Program Files (x86)\Bonjour\mdnsNSP.dll  6EDA0000 - 6EDC1000 v.3.1.0.1 [12 Aug 2015 16:03:38]
C:\Windows\system32\Iphlpapi.DLL  72520000 - 7253C000 v.6.1.7601.17514 [21 Nov 2010 6:24:32]
C:\Windows\system32\WINNSI.DLL  72510000 - 72517000 v.6.1.7601.23889 [11 Aug 2017 9:19:44]
C:\Windows\system32\rasadhlp.dll  6ED90000 - 6ED96000 v.6.1.7600.16385 [14 Jul 2009 4:16:12]
C:\Windows\System32\fwpuclnt.dll  6D250000 - 6D288000 v.6.1.7601.24000 [30 Oct 2018 23:23:22]
C:\Windows\system32\schannel.dll  6D1E0000 - 6D221000 v.6.1.7601.24260 [30 Oct 2018 23:23:19]
C:\Windows\system32\credssp.dll  6D240000 - 6D248000 v.6.1.7601.24260 [30 Oct 2018 23:23:19]
C:\Windows\system32\ncrypt.dll  74250000 - 74289000 v.6.1.7601.24260 [30 Oct 2018 23:23:19]
C:\Windows\system32\bcrypt.dll  74300000 - 74317000 v.6.1.7601.24260 [30 Oct 2018 23:23:19]
C:\Windows\SysWOW64\bcryptprimitives.dll  742C0000 - 742FD000 v.6.1.7601.23451 [12 May 2016 16:04:55]
C:\Windows\system32\CRYPTSP.dll  71EE0000 - 71EF7000 v.6.1.7601.23471 [14 Jun 2016 18:21:20]
C:\Windows\system32\rsaenh.dll  71EA0000 - 71EDB000 v.6.1.7600.16385 [14 Jul 2009 4:17:54]
C:\Windows\system32\msls31.dll  664A0000 - 664D1000 v.3.10.349.0 [25 Oct 2016 19:58:54]
C:\Windows\system32\SXS.DLL  5A190000 - 5A1EF000 v.6.1.7601.17514 [21 Nov 2010 6:24:16]
C:\Windows\system32\MMDevAPI.DLL  6D940000 - 6D979000 v.6.1.7601.17514 [21 Nov 2010 6:23:51]
C:\Windows\system32\PROPSYS.dll  6EC90000 - 6ED85000 v.7.0.7601.17514 [21 Nov 2010 6:24:08]
C:\Windows\system32\wdmaud.drv  58290000 - 582C0000 v.6.1.7601.17514 [21 Nov 2010 6:24:00]
C:\Windows\system32\ksuser.dll  5CA50000 - 5CA54000 v.6.1.7601.19091 [9 Dec 2015 0:53:47]
C:\Windows\system32\AVRT.dll  5D0C0000 - 5D0C7000 v.6.1.7600.16385 [14 Jul 2009 4:14:58]
C:\Windows\syswow64\SETUPAPI.dll  75D80000 - 75F1D000 v.6.1.7601.17514 [21 Nov 2010 6:23:51]
C:\Windows\syswow64\CFGMGR32.dll  77230000 - 77257000 v.6.1.7601.17621 [24 May 2011 13:39:38]
C:\Windows\syswow64\DEVOBJ.dll  75F20000 - 75F32000 v.6.1.7601.17621 [24 May 2011 13:40:05]
C:\Windows\system32\AUDIOSES.DLL  6D8D0000 - 6D906000 v.6.1.7601.23471 [14 Jun 2016 18:21:18]
C:\Windows\system32\msacm32.drv  58400000 - 58408000 v.6.1.7600.16385 [14 Jul 2009 4:14:08]
C:\Windows\system32\MSACM32.dll  58230000 - 58244000 v.6.1.7600.16385 [14 Jul 2009 4:15:42]
C:\Windows\system32\midimap.dll  583F0000 - 583F7000 v.6.1.7600.16385 [14 Jul 2009 4:15:40]

**Comment by dartraiden** [comment] 2019-01-23 14:39
Duplicate of https://github.com/miranda-ng/miranda-ng/issues/1760

**Closed by dartraiden** 2019-01-23 14:39 UTC
Labels: ICQ, blocker, bug, crash
