### ISSUE TITLE
mimcmd (command line)

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#150] opened 2016-10-17 16:40 UTC
**Reported by vanishare on 19 Jan 2013 10:31 UTC**
       (   mimcmd.exe)  (       ,  )  .       ,         mimcmd.exe
        .

```
   ,               .
```

**Comment by georgehazan** [comment] 2016-10-17 16:40
**Modified by mataes on 27 May 2014 07:59 UTC**

**Comment by dartraiden** [comment] 2016-12-11 20:27
Duplicate of #119

**Closed by dartraiden** 2016-12-11 20:27 UTC
Labels: bug, C: cmdline, minor
