### ISSUE TITLE
Discord+core: crash at "RtlInitializeCriticalSection", "delete_scalar_size.cpp (31): operator delete", "internalJSONNode::~internalJSONNode", "gateway.cpp (124): CDiscordProto::GatewayThreadWorker"

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#2494] opened 2020-07-23 09:59 UTC
Discord+core+libjson: crash at
"RtlInitializeCriticalSection", "delete_scalar_size.cpp (31): operator delete", "internalJSONNode::~internalJSONNode", "gateway.cpp (124): CDiscordProto::GatewayThreadWorker"

dump+log: http://coraksoft1.narod.ru/temp/miranda/MirandaCrash_20200713_CDiscordProto_GatewayThreadWorker2.7z

Likely cause of the crash plugin: Discord protocol

Exception: Access Violation at address 7C911980. Reading from address ABBABABA.

Stack Trace:
---------------------------------------------------------------
7C911980 (ntdll 7C900000): (filename not available) (0): RtlInitializeCriticalSection
7C91080B (ntdll 7C900000): (filename not available) (0): wcsncpy
100310FB (ucrtbase 10000000): (filename not available) (0): free_base
100310C8 (ucrtbase 10000000): (filename not available) (0): free
125E2C6C (libjson 125E0000): d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\heap\delete_scalar_size.cpp (31): operator delete
125E2534 (libjson 125E0000): c:\vs2017\vc\tools\msvc\14.16.27023\include\xmemory0 (992): std::allocator<char>::deallocate
125E2554 (libjson 125E0000): c:\vs2017\vc\tools\msvc\14.16.27023\include\xstring (3995): std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy_deallocate
125E4591 (libjson 125E0000): w:\miranda-build\libs\libjson\src\internaljsonnode.cpp (183): internalJSONNode::~internalJSONNode
125E192D (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonnode.inl (247): JSONNode::decRef
125E1B96 (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonnode.inl (399): JSONNode::deleteJSONNode
125E4914 (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonchildren.cpp (82): jsonChildren::deleteAll
125E10BD (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonchildren.h (32): jsonChildren::~jsonChildren
125E4589 (libjson 125E0000): w:\miranda-build\libs\libjson\src\internaljsonnode.cpp (183): internalJSONNode::~internalJSONNode
125E192D (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonnode.inl (247): JSONNode::decRef
125E1B96 (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonnode.inl (399): JSONNode::deleteJSONNode
125E4914 (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonchildren.cpp (82): jsonChildren::deleteAll
125E10BD (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonchildren.h (32): jsonChildren::~jsonChildren
125E4589 (libjson 125E0000): w:\miranda-build\libs\libjson\src\internaljsonnode.cpp (183): internalJSONNode::~internalJSONNode
125E192D (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonnode.inl (247): JSONNode::decRef
125E1B96 (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonnode.inl (399): JSONNode::deleteJSONNode
125E4914 (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonchildren.cpp (82): jsonChildren::deleteAll
125E10BD (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonchildren.h (32): jsonChildren::~jsonChildren
125E4589 (libjson 125E0000): w:\miranda-build\libs\libjson\src\internaljsonnode.cpp (183): internalJSONNode::~internalJSONNode
125E192D (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonnode.inl (247): JSONNode::decRef
125E1B96 (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonnode.inl (399): JSONNode::deleteJSONNode
125E4914 (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonchildren.cpp (82): jsonChildren::deleteAll
125E10BD (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonchildren.h (32): jsonChildren::~jsonChildren
125E4589 (libjson 125E0000): w:\miranda-build\libs\libjson\src\internaljsonnode.cpp (183): internalJSONNode::~internalJSONNode
125E192D (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonnode.inl (247): JSONNode::decRef
125E1B96 (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonnode.inl (399): JSONNode::deleteJSONNode
125E4914 (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonchildren.cpp (82): jsonChildren::deleteAll
125E10BD (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonchildren.h (32): jsonChildren::~jsonChildren
125E4589 (libjson 125E0000): w:\miranda-build\libs\libjson\src\internaljsonnode.cpp (183): internalJSONNode::~internalJSONNode
125E192D (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonnode.inl (247): JSONNode::decRef
125E1B96 (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonnode.inl (399): JSONNode::deleteJSONNode
125E4914 (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonchildren.cpp (82): jsonChildren::deleteAll
125E10BD (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonchildren.h (32): jsonChildren::~jsonChildren
125E4589 (libjson 125E0000): w:\miranda-build\libs\libjson\src\internaljsonnode.cpp (183): internalJSONNode::~internalJSONNode
125E192D (libjson 125E0000): w:\miranda-build\libs\libjson\src\jsonnode.inl (247): JSONNode::decRef
169A520A (Discord 169A0000): w:\miranda-build\protocols\discord\src\gateway.cpp (124): CDiscordProto::GatewayThreadWorker
169A5405 (Discord 169A0000): w:\miranda-build\protocols\discord\src\gateway.cpp (38): CDiscordProto::GatewayThread
129335AB (mir_core 12920000): w:\miranda-build\src\mir_core\src\threads.cpp (161): forkthreadex_r
7C80B729 (kernel32 7C800000): (filename not available) (0): GetModuleFileNameA

**Comment by georgehazan** [comment] 2020-07-24 11:34
duplicate of #2465, memory corruption

**Closed by georgehazan** 2020-07-24 11:34 UTC
Labels: bug

**Comment by erthink** [comment] 2021-02-09 18:06
В пофикшеном баге было указано что это дубликат, а после за полгода не воспроизвелось - видимо можно закрывать?
