### ISSUE TITLE
Discord: crash at "gateway.cpp (120): CDiscordProto::GatewayThreadWorker" and "m_string.inl (552): CMStringT<char,ChTraitsCRT<char> >::CMStringT<char,ChTraitsCRT<char> >"

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#2405] opened 2020-05-16 20:37 UTC
crashlog: http://coraksoft1.narod.ru/temp/miranda/Miranda_crash_20200513_CDiscordProto_GatewayThreadWorker.7z

Likely cause of the crash plugin: Discord protocol

Exception: Access Violation at address 00A7D3E0. Reading from address 01E05000.

Stack Trace:
---------------------------------------------------------------
00A7D3E0 (VCRUNTIME140 00A70000): (filename not available) (0): memcpy
129241C0 (mir_core 12920000): w:\miranda-build\include\m_string.inl (552): CMStringT<char,ChTraitsCRT<char> >::CMStringT<char,ChTraitsCRT<char> >
169A51CE (Discord 169A0000): w:\miranda-build\protocols\discord\src\gateway.cpp (120): CDiscordProto::GatewayThreadWorker
7C80A0C7 (kernel32 7C800000): (filename not available) (0): SetEvent

**Comment by georgehazan** [comment] 2020-05-17 17:11
duplicate of #2404

**Closed by georgehazan** 2020-05-17 17:11 UTC
Labels: bug
