### ISSUE TITLE
Steam plugin: Offline status is wrong

### ISSUE THREAD

**Issue by SmilingSpectre** [miranda-ng/miranda-ng#646] opened 2016-12-08 11:44 UTC
Steam plugin fails to determine contact status sometimes. In most of cases all contacts simply appears in list on login, just as they do for the any other protocol. But about in 1/6 cases nothing happens. Steam is connected (and even shows me incoming messages, if any), but everyone are offline. Sending reples to this people works, but I haven't idea if they really reaches anyone: usually I am restarting plugin right away, and that fixes the issue.

Also, I noticed that later _some_ people (probably, appeared after plugin was started) appeared in the "online" state, even if Steam missed everyone before (and I didn't notice that in time). But "full" list never re-appears that makes the problem even more confusing.

**Comment by LittleVulpix** [comment] 2016-12-08 12:10
@SmilingSpectre this happens if you lose connection, or if you disconnect from steam too quickly (or incorrectly) and then sign in right away. This for some reason causes everyone BUT people whose status changes to appear offline.  (http://forum.miranda-ng.org/index.php?topic=1222.msg16291#msg16291 / http://forum.miranda-ng.org/index.php?topic=1222.msg16290#msg16290 )

**Comment by SmilingSpectre** [comment] 2016-12-08 14:55
@LittleVulpix I seen your messages, but it implies that problem will fix itself eventually. In my experience, it fixes only people who went online/offline in this session - so anyone who is keep logged will be invisible whole session. :/ Well, if it's not plugin error but system error of the protocol, then a little can be done... but it still the error for me. :/

**Comment by LittleVulpix** [comment] 2016-12-08 15:14
Hello, yes it will not fix itself eventually :( as you said only for people who changed their status. So if someone is already online and doesn't go away or something , you will never see them. The only resolution for now is to log off and log back on. I agree it is a bug.

**Comment by unitwobble** [comment] 2016-12-08 21:03
I cannot confirm if this is actually doing something or it's total blind luck on my end: Turning "Show chat events" off and reconnecting will cause the contact list to work as normal. I must be mistaken since ShowChatEvents only shows up in one line: steam_polling.cpp:159.

**Comment by LittleVulpix** [comment] 2016-12-08 22:28
@unitwobble it just fixes itself regardless of any settings, as long as you reconnect when you notice it.

**Comment by unitwobble** [comment] 2016-12-10 05:00
@LittleVulpix
Do you think it would be a good idea to uncomment steam_contacts.cpp line 176 to let it use personastate? At least the contact list will be correct(?) when you log in and receive the GetUserSummaries reply.

**Comment by unitwobble** [comment] 2016-12-10 05:52
@LittleVulpix
Do you think it would be a good idea to uncomment steam_contacts.cpp line 176 to let it use personastate? At least the contact list will be correct(?) when you log in and receive the GetUserSummaries reply.

**Comment by Robyer** [comment] 2016-12-11 21:44
@unitwobble I uncommented it, but I'm not sure it's a good idea (I just don't remember what else it affects). So you can tell me if it solves this problem or improves it somehow (or if it breaks some other functionality).

**Comment by unitwobble** [comment] 2016-12-12 19:22
@Robyer Thanks! The contact list now shows users online when logging in. Too early to tell if it has any side effects but contact list updates work as normal so far (contact switching to away, playing games, etc.)

**Comment by LittleVulpix** [comment] 2016-12-12 19:32
I agree. Too early to tell here as well but for now it doesn't seem like any functionality is impacted. I'll post here after a few days.

**Comment by Robyer** [comment] 2016-12-12 19:35
When I tried to reproduce the problem, even when I connected/disconnected quickly for many times, it happened to me only once (maybe from 10 tries or more). So I'm not sure if this change really helped.

Also reading from my comment in code, it won't work for users with disabled public profile. Do you have any such contact to test with?

**Comment by LittleVulpix** [comment] 2016-12-12 19:42
Me! :D you have me on steam, and I have private profile. Try it, @Robyer

**Comment by SmilingSpectre** [comment] 2016-12-12 20:13
>even when I connected/disconnected quickly for many times, it happened to me only once (maybe from 10 tries or more)

@Robyer , you are lucky. I have contact issue half of time - and so two connect/disconnect is not very uncommon, and sometimes it requires 3 times or more. :) Possibly, your line is much better than mine.

**Comment by Robyer** [comment] 2016-12-12 20:31
@LittleVulpix I just can't reproduce it :D (I just tried)

@SmilingSpectre Hmm, maybe you've got something... I have good internet, so if it is related to that, maybe the problem is that some request delay start of the polling thread, so when we are in the middle of connecting, Steam already gives us list of contacts, but we are not receiving it yet (as we are still internally waiting for something else). I'll check the code some other day, if this could make sense... Or netlog could possibly help.

Could some of you provide netlog capturing the problem? And then netlog from reconnect that fixes it?

**Comment by unitwobble** [comment] 2016-12-15 14:43
@Robyer This is the only indication why it's not working and it doesn't say anything useful. The polling thread quits (without sending the polling API request) when it is started on login and it doesn't get called again. All the other API requests work as normal.

[00:59:48 164C] [STEAM_1] CSteamProto::PollingThread: entering
[00:59:48 164C] [STEAM_1] CSteamProto::PollingThread: leaving

Polling thread working is very rare (1 in 10 tries or more) for me so I hope someone can get the logs for you to compare.

**Comment by Robyer** [comment] 2016-12-15 15:16
@unitwobble So you are saying that when the issue happens, pollingthread quits without sending any request, is not called again and plugin then *still works correctly*?

In original post is: 
> Steam is connected (and even shows me incoming messages, if any), but everyone are offline.

**Comment by unitwobble** [comment] 2016-12-15 19:52
@Robyer Log on its way. But there's one thing I never tested: Sending messages. The API will report not logged on:
CSteamProto::OnMessageSent: failed to send message for 7 (Not Logged On)
So I guess it works for the most part... until you want to send a message.

**Comment by unitwobble** [comment] 2016-12-15 20:24
Just tested this: While Pollingthread is dead, If you get a message when you log on you can send replies to the person (but will return Not Logged On error for anyone else). Also you will appear offline to everyone (including the person you just replied).

**Comment by LittleVulpix** [comment] 2016-12-16 09:30
@Robyer I noticed that steam status is now wrong. It shows people online who are no longer online, or it shows people playing games they no longer play. I had 19 people online and when I logged out and back in, I had 11 (I noticed something was strange because a person who was at work was shown as playing Rocket League, so I clicked their steam page and it said they weren't even online).

I think you should re-comment back the personastate thing, it seems to have broken some things... I don't remember this happening previously.

**Comment by Robyer** [comment] 2016-12-16 13:31
@LittleVulpix Thanks for info, I will. If this issue is about dead pollingthread, that sounds much better to find the problem and solve it.

**Comment by Robyer** [comment] 2016-12-25 11:54
@unitwobble Thanks for logs. Dying polling thread should be fixed now.

Maybe this fixes also this whole ticket. @SmilingSpectre @LittleVulpix , please let me know after you test next build (tomorrow).

**Comment by unitwobble** [comment] 2016-12-25 12:57
@Robyer Thank you so much and merry christmas!

**Comment by LittleVulpix** [comment] 2016-12-28 08:22
@robyer I have not had any issues with the steam protocol since. This one time it took like a minute to sign in or so, but it showed all states correctly.

**Comment by Robyer** [comment] 2016-12-28 14:21
Hmm, that's disappointing... I'll contact you later about the netlog.

**Comment by aunsane** [comment] 2018-01-17 20:20
Hi all! Please check it to next nightly.

**Comment by LittleVulpix** [comment] 2018-01-17 20:28
Will do when it's compiled! Thanks @aunsane !

**Comment by LittleVulpix** [comment] 2018-01-21 10:13
@aunsane I think this works as intended now, I tried relogging a few times quickly but I never saw the bug.

**Closed** 2018-01-21 21:17 UTC
Labels: Steam
