### ISSUE TITLE
Miranda G15 plugin stops working when Logitech Gaming Software loads when Miranda NG is already running

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#246] opened 2016-10-17 19:11 UTC
**Reported by Llewen on 3 Dec 2013 02:08 UTC**
Miranda NG used to crash in this context, but now it is just the plugin that stops working.  I don't know if it doesn't reload into the Logitech Gaming software, or whether it crashes, or is stopped somehow, but I know this didn't used to happen with the original Miranda G15 plugin.  There were no issues with the plugin not starting with the Logitech Gaming Software with Miranda IM.

The typical context this happens in is on return from Windows sleep when the Logitech Gaming Software has to be restarted.

**Comment by georgehazan** [comment] 2016-10-17 19:11
**Modified by mataes on 27 May 2014 04:29 UTC**

**Comment by dartraiden** [comment] 2016-12-12 12:46
Duplicate of #240

**Closed by dartraiden** 2016-12-12 12:46 UTC
Labels: bug, C: mirandag15, major
