### ISSUE TITLE
TabsRmm: crash on start in "srmm_base.cpp (474): CSrmmBaseDialog::OnInitDialog" and "msgdialog.cpp (384): CMsgDialog::OnInitDialog"

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#2874] opened 2021-05-08 12:01 UTC
Core+TabsRmm: 
crash on start in "srmm_base.cpp (474): CSrmmBaseDialog::OnInitDialog" and "msgdialog.cpp (384): CMsgDialog::OnInitDialog" #2874

[mirandang-crash-CSrmmBaseDialog-OnInitDialog-20210507.zip](https://github.com/miranda-ng/miranda-ng/files/6447533/mirandang-crash-CSrmmBaseDialog-OnInitDialog-20210507.zip)

```
Likely cause of the crash plugin: Miranda NG

Exception: Access Violation at address 12B5BF78. Reading from address 00000000.

Stack Trace:
---------------------------------------------------------------
12B5BF78 (mir_app 12B00000): w:\miranda-build\src\mir_app\src\srmm_base.cpp (474): 
186A3CC4 (TabSRMM 18680000): w:\miranda-build\plugins\tabsrmm\src\msgdialog.cpp (384): CMsgDialog::OnInitDialog
12CCBE57 (mir_core 12CC0000): w:\miranda-build\src\mir_core\src\cdlgbase.cpp (218): CDlgBase::DlgProc
12B5BEE8 (mir_app 12B00000): w:\miranda-build\src\mir_app\src\srmm_base.cpp (548): CSrmmBaseDialog::DlgProc
186A0F4F (TabSRMM 18680000): w:\miranda-build\plugins\tabsrmm\src\msgdialog.cpp (3101): CMsgDialog::DlgProc
12CCB9F1 (mir_core 12CC0000): w:\miranda-build\src\mir_core\src\cdlgbase.cpp (413): CDlgBase::GlobalDlgProc
7E418734 (USER32 7E410000): (filename not available) (0): GetDC
7E42D158 (USER32 7E410000): (filename not available) (0): DefDlgProcW
7E42C9E0 (USER32 7E410000): (filename not available) (0): SendDlgItemMessageW
7E42CC0C (USER32 7E410000): (filename not available) (0): DefDlgProcW
7E418734 (USER32 7E410000): (filename not available) (0): GetDC
7E418816 (USER32 7E410000): (filename not available) (0): GetDC
7E41B8AB (USER32 7E410000): (filename not available) (0): GetParent
7E42BA37 (USER32 7E410000): (filename not available) (0): IsDlgButtonChecked
7E42BD5B (USER32 7E410000): (filename not available) (0): CreateDialogIndirectParamAorW
7E424834 (USER32 7E410000): (filename not available) (0): CreateDialogParamW
12CCC1AD (mir_core 12CC0000): w:\miranda-build\src\mir_core\src\cdlgbase.cpp (105): CDlgBase::Create
12CCB995 (mir_core 12CC0000): w:\miranda-build\src\mir_core\src\cdlgbase.cpp (402): CDlgBase::GlobalDlgProc
03CF4CD8 ((module-name not available) 00000000): (filename not available) (0): (function-name not available)
1868E5F4 (TabSRMM 18680000): w:\miranda-build\plugins\tabsrmm\src\container.cpp (2293): AutoCreateWindow
02361060 (wheel 02360000): (filename not available) (0): SetTrayParams
```
"

**Comment by georgehazan** [comment] 2021-05-13 19:01
duplicate of #2871

**Closed by georgehazan** 2021-05-13 19:01 UTC
Labels: TabSRMM, bug, crash
