### ISSUE TITLE
Facebook - Error 406

### ISSUE THREAD

**Issue by Dvorak-Stepan** [miranda-ng/miranda-ng#2970] opened 2021-11-16 12:16 UTC
I changed my Facebook password today. Since then, I can't log in to Miranda via Facebook. It still reports error 406. Also tried a completely clean install of Miranda. I use 2FA on Facebook. Confirmation doesn't help and I have nowhere to write the control code.

**Comment by dartraiden** [comment] 2021-11-16 12:57
Duplicate of https://github.com/miranda-ng/miranda-ng/issues/2163

**Closed by dartraiden** 2021-11-16 12:57 UTC
Labels: bug

**Comment by dartraiden** [comment] 2021-11-16 13:05
Also see https://github.com/miranda-ng/miranda-ng/issues/2207#issuecomment-585791499

**Comment by Dvorak-Stepan** [comment] 2021-11-16 13:34
Turn off 2FA? Good joke!
I'd rather wait and see if anything changes over time.
