### ISSUE TITLE
Crashes after large files has been transferred

### ISSUE THREAD

**Issue by Skeevy** [miranda-ng/miranda-ng#1040] opened 2017-11-23 17:58 UTC
### Expected behavior
No crash

### Actual behavior
Miranda NG crashes frequently, when large files are transitted. (Peer to peer)

### Does it work in stable version?
We're experiencing this issue since several months. There have been many updates since then and we always hope this will be addressed, but it still happens.

### Steps to reproduce that behavior
Transfer a large files via peer to peer (ICQ protocol) with a size of several MBs. It usually doesn't happen for very short files.

The file transmission itself is working fine (and many thanks for fixing the multiple connection issues), but immediately after the files has been transmitted, the client that sended the file crashes.

I tried to locate a crashdumper log, but it seems no dumps are created.

We're all using the latest builds:

[MirandaVersion.txt](https://github.com/miranda-ng/miranda-ng/files/1500000/MirandaVersion.txt)

Thanks for all support,
Kind Regards,
Skeevy

**Comment by dartraiden** [comment] 2017-11-23 19:02
Duplicate of #920

**Closed by dartraiden** 2017-11-23 19:02 UTC
Labels: bug, crash, ICQ
