### ISSUE TITLE
IRC connecting but never online

### ISSUE THREAD

**Issue by XP-Fan** [miranda-ng/miranda-ng#1604] opened 2018-09-26 22:19 UTC
When I am connecting to the IRC-Server of whappirc (an whatsapp web/IRC-Gateway), Miranda NG doesn't get that it is online. It always says connecting, thus it is possible to receive messages, but not to send anything, which sucks.

**Comment by georgehazan** [comment] 2018-09-27 10:05
attach a network log, please
https://wiki.miranda-ng.org/index.php?title=Network_log

**Comment by XP-Fan** [comment] 2018-09-27 14:29
Well yeah, this would contain my password wouldn't it?

**Comment by georgehazan** [comment] 2018-09-27 14:32
> Well yeah, this would contain my password wouldn't it?

you can remove it from that file. Otherwise I cannot understand what's going on

**Comment by XP-Fan** [comment] 2018-09-27 16:32
Allright, but I would then prefer to give you the file privately.

**Comment by georgehazan** [comment] 2018-09-27 18:15
sure. email it to ghazan at miranda point im.

**Comment by dartraiden** [comment] 2018-10-06 12:33
Duplicate of #719

**Closed by dartraiden** 2018-10-06 12:33 UTC
Labels: IRC, enhancement

**Comment by lieuwex** [comment] 2018-10-07 21:06
FWIW the issue for connecting has been fixed at whapp-irc's side (I didn't send a MOTD, sorry). 

https://github.com/lieuwex/whapp-irc/issues/28 is the discussion on my side about whapp-irc <-> miranda-ng compatibility issues.
