### ISSUE TITLE
Core (Chat): crash on "utils.cpp (464): mir_wstrcmp" and "chat_manager.cpp (34): CompareKeys"

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#2031] opened 2019-08-13 15:46 UTC
```
Likely cause of the crash plugin: Miranda NG

Exception: Access Violation at address 128B860E. Reading from address DEADBEEF.

Stack Trace:
---------------------------------------------------------------
128B860E (mir_core 128A0000): w:\miranda-build\src\mir_core\src\utils.cpp (464): mir_wstrcmp
12714AC8 (mir_app 12700000): w:\miranda-build\src\mir_app\src\chat_manager.cpp (34): CompareKeys
128AECA6 (mir_core 128A0000): w:\miranda-build\src\mir_core\src\lists.cpp (138): List_GetIndex
128AEDCA (mir_core 128A0000): w:\miranda-build\src\mir_core\src\lists.cpp (56): List_Find
12713D3A (mir_app 12700000): w:\miranda-build\src\mir_app\src\chat_manager.cpp (685): UM_FindUser
12713A26 (mir_app 12700000): w:\miranda-build\src\mir_app\src\chat_manager.cpp (818): UM_TakeStatus
1271447E (mir_app 12700000): w:\miranda-build\src\mir_app\src\chat_manager.cpp (312): SM_TakeStatus
12716811 (mir_app 12700000): w:\miranda-build\src\mir_app\src\chat_svc.cpp (509): sttEventStub
128B0371 (mir_core 128A0000): w:\miranda-build\src\mir_core\src\modules.cpp (644): CallFuncToMainAPCFunc
128B008A (mir_core 128A0000): w:\miranda-build\src\mir_core\src\miranda.cpp (81): APCWndProc
7E368734 (USER32 7E360000): (filename not available) (0): GetDC
7E368816 (USER32 7E360000): (filename not available) (0): GetDC
7E3689CD (USER32 7E360000): (filename not available) (0): GetWindowLongW
7E368A10 (USER32 7E360000): (filename not available) (0): DispatchMessageW
127457ED (mir_app 12700000): w:\miranda-build\src\mir_app\src\miranda.cpp (381): mir_main
004023E5 (Miranda32 00400000): w:\miranda-build\src\miranda32\src\miranda.cpp (62): wWinMain
004013C9 (Miranda32 00400000): d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl (288): __scrt_common_main_seh
7C81776F (kernel32 7C800000): (filename not available) (0): RegisterWaitForInputIdle
```

[Mirandang_Crash_20190813_Chat_Manager_Cpp_34_Comparekeys.zip](https://github.com/miranda-ng/miranda-ng/files/3502872/Mirandang_Crash_20190813_Chat_Manager_Cpp_34_Comparekeys.zip)

**Comment by Corak667** [comment] 2019-08-13 15:46
memdump:
http://coraksoft1.narod.ru/temp/miranda/Mirandang_Crash_20190813_Chat_Manager_Cpp_34_Comparekeys.zip

**Comment by georgehazan** [comment] 2019-08-21 16:29
duplicate of #2027

**Closed by georgehazan** 2019-08-21 16:29 UTC
Labels: bug, core, crash
