### ISSUE TITLE
new ICQ messages are not shown in messages windows

### ISSUE THREAD

**Issue by sdv3** [miranda-ng/miranda-ng#1420] opened 2018-06-13 04:43 UTC
### Expected behavior
ICQ messages should be shown in the proper dialog window instantly, as soon as they are send or received

### Actual behavior
ICQ messages are shown in the proper dialog window only when the window is reopened. New messages still do not appear. Realtime tracking is possible only through History.

### Does it work in stable version?
Started with the last update 0.95.8.1 09.06.2018

### Steps to reproduce that behavior
Miranda 0.95.8.1 b19974 x64
icq.dll 0.95.8.1
plugins installed: modern contact list, clist nicer, cryto++, dummy protocol, history++, icqoscarj protocol, import contacts and messages, jabber protocol, plugin updater, scriver, stopspam+, toptoolbar, tox protocol

**Comment by dartraiden** [comment] 2018-06-13 09:01
What message plugin? Scriver?

**Comment by Goraf** [comment] 2018-06-13 10:07
Yep, Scriver. It is mentioned at the end of the description.

**Comment by dartraiden** [comment] 2018-06-13 10:07
Ok.

**Comment by dartraiden** [comment] 2018-06-13 10:07
Duplicate of #1413

**Closed by dartraiden** 2018-06-13 10:07 UTC
