### ISSUE TITLE
Already read messages are displayed again and again in the SysTray

### ISSUE THREAD

**Issue by winman3000** [miranda-ng/miranda-ng#4277] opened 2024-03-11 16:58 UTC
# Already read messages are displayed again and again in the SysTray

When I start Miranda NG (daily build), the messages I have already read are still displayed in the SysTray. I cannot get rid of them.

### Steps to reproduce

1. Receive a message on Facebook or an XMPP based protocol.
1. Something like "Message from XY" is displayed in the SysTray, where "XY" stands for the person who has just written.
1. Press CTRL+Shift+I to open the message window and read the message.
1. Close the message window with Escape.
1. Quit Miranda NG and start it again.

#### Result

The message that has already been read is still visible in the SysTray. "New message from XY" is still displayed, although there are no new messages from this person.

#### Expected

The message "Message from XY" should no longer be displayed if all messages have been read.

## Version info

[spoiler=VersionInfo][quote]CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz [Intel64 Family 6 Model 58 Stepping 9] [DEP Enabled] [8 CPUs]
Installed RAM: 16316 MBytes
Microsoft Windows 10 , 64-bit (build 22621)
Internet Explorer: 9.11.22621.0 (build 922621)
Administrator privileges: No
OS Languages: (UI | Locale (User/System)) : German/German | German/German
Free disk space on Miranda partition: 839709 MBytes

Miranda NG Version: 0.96.5 alpha build #26957 (d43ae9445d) x64
Build time: Sonntag, 10. März 2024 19:23:30
Profile: C:\Users\winma\AppData\Roaming\Miranda NG\Ali\Ali.dat
Database driver: SQLite database driver
Profile size: 37707776 Bytes
Profile creation date: Samstag, 16. November 2019 22:51:45
Language pack: German (DE) [0407]
Service Mode: No
SRMM Log Viewer: built-in

[b]Active Plugins (20):[/b]
¤ AVS.dll v.[b]0.98.1.6[/b] [Samstag, 2. März 2024 12:50:50] - Avatar service 
¤ Clist_blind.dll v.[b]0.9.0.1[/b] [Freitag, 23. Februar 2024 20:28:40] - BClist 
¤ CrashDumper.dll v.[b]0.2.0.3[/b] [Samstag, 2. März 2024 12:51:38] - Crash dumper 
¤ Db_autobackups.dll v.[b]0.1.0.7[/b] [Sonntag, 10. März 2024 19:23:50] - Db autobackuper 
¤ DbChecker.dll v.[b]0.96.4.1[/b] [Sonntag, 10. März 2024 19:25:58] - Database checker 
¤ DbEditorPP.dll v.[b]4.1.0.4[/b] [Freitag, 23. Februar 2024 20:28:14] - Database editor++ 
¤ Dbx_mdbx.dll v.[b]0.95.9.1[/b] [Freitag, 23. Februar 2024 20:34:08] - Miranda NG MDBX database driver 
¤ Dbx_sqlite.dll v.[b]0.96.4.1[/b] [Sonntag, 10. März 2024 19:25:52] - Miranda NG SQLite database driver 
¤ Dummy.dll v.[b]0.2.0.1[/b] [Sonntag, 10. März 2024 19:25:22] - Dummy protocol 
¤ Facebook.dll v.[b]0.1.0.11[/b] [Sonntag, 10. März 2024 13:27:12] - Facebook 
¤ GG.dll v.[b]0.96.3.1[/b] [Freitag, 23. Februar 2024 20:28:00] - Gadu-Gadu protocol 
¤ historypp.dll v.[b]1.5.1.5[/b] [Samstag, 27. Januar 2024 12:54:42] - History++ 
¤ ICQ.dll v.[b]0.96.5.1[/b] [Sonntag, 25. Februar 2024 11:49:36] - ICQ-WIM protocol 
¤ Import.dll v.[b]0.96.3.1[/b] [Sonntag, 10. März 2024 19:24:06] - Import contacts and messages 
¤ IRC.dll v.[b]0.96.1.4[/b] [Samstag, 2. März 2024 12:50:50] - IRC protocol 
¤ Jabber.dll v.[b]0.95.11.1[/b] [Sonntag, 10. März 2024 13:25:26] - Jabber protocol 
¤ MessageState.dll v.[b]0.1.0.2[/b] [Sonntag, 10. März 2024 13:26:44] - Message state 
¤ PluginUpdater.dll v.[b]0.2.1.7[/b] [Freitag, 23. Februar 2024 20:28:24] - Plugin updater 
¤ Tox.dll v.[b]0.96.4.1[/b] [Freitag, 23. Februar 2024 20:30:00] - Tox protocol 
¤ VoiceService.dll v.[b]0.1.3.2[/b] [Freitag, 23. Februar 2024 20:29:48] - Voice Service 

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
Facebook                 2 - Enabled 0 - Disabled  Loaded
ICQ                      1 - Enabled 0 - Disabled  Loaded
JABBER                   1 - Enabled 0 - Disabled  Loaded
TOX                      1 - Enabled 0 - Disabled  Loaded
WhatsApp                 1 - Enabled 0 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 HistoryPP_icons.dll [Samstag, 27. Januar 2024 12:54:36]
 Proto_Discord.dll [Dienstag, 1. März 2022 13:53:57]
 Proto_Dummy.dll [Sonntag, 10. März 2024 19:30:22]
 Proto_Facebook.dll [Sonntag, 10. März 2024 13:31:22]
 Proto_GG.dll [Freitag, 23. Februar 2024 20:34:14]
 Proto_ICQ.dll [Sonntag, 25. Februar 2024 11:53:58]
 Proto_IRC.dll [Samstag, 2. März 2024 12:57:48]
 Proto_Jabber.dll [Sonntag, 10. März 2024 13:31:20]
 Proto_MetaContacts.dll [Sonntag, 10. März 2024 19:30:22]
 Proto_MRA.dll [Sonntag, 25. Februar 2024 11:53:58]
 Proto_Tox.dll [Freitag, 23. Februar 2024 20:34:16]
 xStatus_Jabber.dll [Sonntag, 10. März 2024 13:31:22]
[/quote][/spoiler]

**Comment by winman3000** [comment] 2024-03-14 19:40
@georgehazan: Since I went back to the version where it still worked, I can't test it right now. I'll test it at the weekend when I have more time.

However, I have also noticed that Miranda NG does not mark the messages on the server as "read" either. On Facebook, for example, the messages were still all unread. This was also not the case with a previous version of Miranda NG.

**Comment by winman3000** [comment] 2024-03-17 09:35
FYI: I still need some time to analyze the problem. So far I have not received any messages via Facebook, so I have not been able to investigate the problem further. So I ask you to leave this issue open.

**Comment by winman3000** [comment] 2024-03-18 18:26
@georgehazan: If I mark all events as read using the "Check database" function, the messages no longer appear. However, this only solves my problem temporarily, because when the next message arrives, I have the same problem again. Also, the messages are not marked as read on the Facebook server.

**Comment by winman3000** [comment] 2024-03-19 17:40
@georgehazan: is there anything I can provide to help you to solve this problem?

**Comment by georgehazan** [comment] 2024-03-19 17:45
@winman3000 yes, as I've written before - try to find smth related to SQLITE in your network log

**Comment by winman3000** [comment] 2024-03-19 18:23
@georgehazan: Do I have to wait for a specific event (such as a new message) or is it enough to enable logging and restart Miranda NG?

**Comment by georgehazan** [comment] 2024-03-19 18:26
no, you don't have to restart Miranda after applying any option
just wait for the first event which isn't marked read, then stop logging and try to find a string SQLITE in it, especially in the combination with error code 11

**Comment by winman3000** [comment] 2024-03-19 18:44
@georgehazan: OK. I can't find anything about "SQLite" in the log file. However, I was able to narrow down the following:

* When I receive a message from Facebook and press sTRG+Shift+I to open the message window, the event seems to be marked as read, as I originally expected.
* When I restart Miranda NG, the message appears again. Even if I display the message again with CTRL+Shift+I, it is not marked as read.

Can I post my log here without hesitation or should I send you an e-mail?

**Comment by georgehazan** [comment] 2024-03-20 08:32
> Can I post my log here without hesitation or should I send you an e-mail?

You can attach it here, zipped, or send it to me via e-mail, your choice.

**Comment by georgehazan** [comment] 2024-03-20 08:33
@winman3000 btw, have I understood you correctly that an event blinks in the systray only, but doesn't in contact list?

**Comment by winman3000** [comment] 2024-03-20 15:13
[netlog.zip](https://github.com/miranda-ng/miranda-ng/files/14668575/netlog.zip)

@georgehazan: Attached you will find the log file.

I don't know if it's the events in general or just the systray. In any case, sometimes the messages on facebook are not marked as read, but sometimes they are.

Now I also have the problem that the online contacts on facebook are no longer displayed, although facebook is displayed as online. Should I open a different issue for this?

**Comment by winman3000** [comment] 2024-03-20 19:11
> Now I also have the problem that the online contacts on facebook are no longer displayed, although facebook is displayed as online. Should I open a different issue for this?

OK, the contacts from Facebook are displayed again, apparently this was only temporary. However, the actual problem remains.

**Comment by georgehazan** [comment] 2024-03-21 08:10
Yes, it seems that there're no problems with db, but I can't reproduce this problem on StdMsg... the only idea I have is the following one: in theory, if the previous conversation was long enough not to fit into the log window, it's possible that the upper messages won't be marked as read, if they were written to you when a window was closed. If you go up through the log, will it mark events as read?

**Comment by winman3000** [comment] 2024-03-21 09:45
@georgehazan: I'll give it a try, but I don't think it will do any good. It wasn't like that in the previous versions either. It's only been like this for a few days.

**Comment by georgehazan** [comment] 2024-03-21 09:47
Well, this issue mostly is about NewStory, the native logs shall not be affected if you've chosen "Display all unread events"

**Comment by winman3000** [comment] 2024-03-21 16:19
@georgehazan: I have just received messages from two different users on Facebook. Only the last message remains in the SysTray. Navigating in the chat history did not help either.

Changes must have been made in the last few days, causing this behavior. If I restore my backup from March 17, 2024, everything works as expected.

**Comment by winman3000** [comment] 2024-03-23 09:31
@georgehazan: Now it's getting stranger and stranger. I received a message from another Facebook contact last night. It behaves as follows:

* After receiving the message, press CTRL+Shift+I to open the chat window.
* Read the message and press Escape.
The message no longer appears as unread in the SysTray.
* Restart Miranda NG.
The already read message appears again in the systray.
* Repeat the steps listed above.
It always goes round in circles until the event is marked as read in the database.

Incidentally, it seems that the messages on Facebook are not marked as read.

I have the same behavior with XMPP based protocols.

**Comment by dartraiden** [comment] 2024-03-23 17:01
Got it yesterday I opened and read the message, but it continued to blink in the tray and contact list until another message came from the contact.

**Closed** 2024-03-26 10:12 UTC
