### ISSUE TITLE
Crash when receiving file via ICQ

### ISSUE THREAD

**Issue by sagamusix** [miranda-ng/miranda-ng#920] opened 2017-09-07 10:41 UTC
### Expected behavior
Miranda NG should not crash.

### Actual behavior
After receiving a file from another ICQ user (using Pidgin), the file is stored successfully on disk but Miranda NG crashes instantly.

### Does it work in stable version?
No, this is 0.95.6 stable.

**Comment by georgehazan** [comment] 2017-09-07 10:53
switch to development version with symbols & provide a crash log

**Comment by dartraiden** [comment] 2017-09-08 14:00
Possibly related with #700

**Comment by georgehazan** [comment] 2017-09-08 14:01
yes, it's a duplipcate of #700, but the old one got closed

**Comment by Robyer** [comment] 2017-09-09 08:27
@georgehazan Have you looked at the commits that caused the crash appear for first time? As I mentioned them here: https://github.com/miranda-ng/miranda-ng/issues/700#issuecomment-277558315

> WORKS: DB_AUTH_BLOB: handy piece of code moved into the core	16.01.2017 16:20	George Hazan
> WORKS:	- constructor & destructor for NetlibBoundPort - warning fix - randomizer must work even if the s...	17.01.2017 13:56	George Hazan
> WORKS:	code cleaning	17.01.2017 14:08	George Hazan
> CRASHES:	useless field DBEVENTINFO::cbSize removed	17.01.2017 15:19	George Hazan

**Comment by georgehazan** [comment] 2017-09-09 08:30
yes, sure. this field was never used but for structure size checking (despite the Import plugin, but it's definitely not the case), so...

**Comment by Robyer** [comment] 2017-09-09 08:42
So how is possible that it started crashing right with that commit?

**Comment by georgehazan** [comment] 2017-09-09 08:46
¯\_(ツ)_/¯
I added one commit to #700

**Comment by Huhnmann** [comment] 2017-10-24 15:22
Sometimes it crashes when sending a file (and aborting the transfer) (via ICQ), too.

**Comment by dergilb99** [comment] 2017-11-20 16:10
This is a pretty annoying bug.

Four file transfers via Miranda NG (ICQ), four crashes (3x my Miranda NG, 1x receiver's Miranda NG).

**Comment by georgehazan** [comment] 2017-11-22 14:20
@dergilb99 got a crash log?

**Comment by dergilb99** [comment] 2017-11-22 17:26
@georgehazan Yes.

1. Transfer cancelled, because transfer did not start (for what reason ever) -> no problem
2. Transfer cancelled (another file), cancelled after transfer began -> Miranda crashed.

(I added the second empty line, otherwise in preview end of line was ignored for all lines.)
`
[18:13:21 3DD4] [ICQ_1] Init file send

[18:13:21 3DD4] [ICQ_1P2P] OFT: FT struct 000000000C219180 created
[18:13:21 3DD4] [ICQ_1] OFT: Found 1 files.
[18:13:21 3DD4] UPnP disabled. Internal Port: 12052
[18:13:21 3CE0] [ICQ_1P2P] (2456) Port 12052 opened for incoming connections
[18:13:21 3DD4] [ICQ_1] Rates: New level 4500 for #3
[18:13:21 152C] [ICQ_1] Server FLAP: Channel 2, Seq 56310, Length 203 bytes
[18:13:21 152C] [ICQ_1]  Received SNAC(x01,x0A), version 4
[18:13:21 152C] [ICQ_1] Rates: New level 6000 for #1
[18:13:21 3CE0] [ICQ_1P2P] New incoming connection on port 12052 from xxx.xxx.xxx.xxx:65071 (000000000000097C)
[18:13:21 152C] [ICQ_1] Server FLAP: Channel 2, Seq 56311, Length 232 bytes
[18:13:21 152C] [ICQ_1]  Received SNAC(x04,x07)
[18:13:21 152C] [ICQ_1] Message (format 2) - UID: 12345678
[18:13:21 152C] [ICQ_1] Command is 2
[18:13:21 152C] [ICQ_1P2P] OFT: Session established.
[18:13:30 3DD4] [ICQ_1P2P] OFT: Transfer cancelled.
[18:13:30 3DD4] [ICQ_1] Rates: New level 4500 for #3
[18:13:30 3DD4] [ICQ_1P2P] (000000000C8C5A60:2428) Connection closed internal
[18:13:30 00C8] [ICQ_1P2P] Abortive closure of oscar socket (000000000C8C5A60) (10038)
[18:13:30 3DD4] [ICQ_1P2P] (000000000C8C5A60:4294967295) Connection closed
[18:13:30 3CE0] [ICQ_1P2P] NetlibBindAcceptThread (FFFFFFFFFFFFFFFF): accept V4 failed (10038)
[18:13:30 3CE0] [ICQ_1P2P] NetlibBindAcceptThread: (FFFFFFFFFFFFFFFF) thread for port 12052 closed
[18:13:30 3DD4] [ICQ_1P2P] (4294967295) Port 12052 closed for incoming connections
[18:13:30 3DD4] [ICQ_1P2P] Oscar listener on port 12052 released.
[18:13:30 3DD4] [ICQ_1P2P] OFT: FT struct 000000000014DBE0 released
[18:13:31 152C] [ICQ_1] Server FLAP: Channel 2, Seq 56312, Length 203 bytes
[18:13:31 152C] [ICQ_1]  Received SNAC(x01,x0A), version 4
[18:13:31 152C] [ICQ_1] Rates: New level 6000 for #1
[18:13:34 3DD4] [ICQ_1] Init file send
[18:13:34 3DD4] [ICQ_1P2P] OFT: FT struct 000000000C219180 created
[18:13:34 3DD4] [ICQ_1] OFT: Found 1 files.
[18:13:34 3DD4] UPnP disabled. Internal Port: 12053
[18:13:34 302C] [ICQ_1P2P] (2436) Port 12053 opened for incoming connections
[18:13:34 3DD4] [ICQ_1] Rates: New level 4496 for #3
[18:13:34 152C] [ICQ_1] Server FLAP: Channel 2, Seq 56313, Length 203 bytes
[18:13:34 152C] [ICQ_1]  Received SNAC(x01,x0A), version 4
[18:13:34 152C] [ICQ_1] Rates: New level 6000 for #1
[18:13:34 302C] [ICQ_1P2P] New incoming connection on port 12053 from xxx.xxx.xxx.xxx:65074 (00000000000009D8)
[18:13:34 152C] [ICQ_1] Server FLAP: Channel 2, Seq 56314, Length 232 bytes
[18:13:34 152C] [ICQ_1]  Received SNAC(x04,x07)
[18:13:34 152C] [ICQ_1] Message (format 2) - UID: 12345678
[18:13:34 152C] [ICQ_1] Command is 2
[18:13:34 152C] [ICQ_1P2P] OFT: Session established.
[18:13:34 230C] [ICQ_1P2P] OFT: Receiver ready.
`

**Comment by dergilb99** [comment] 2017-11-23 12:04
This seems to happen primarily with larger (~200MB) files.

**Comment by sagamusix** [comment] 2017-11-23 12:05
I've also seen it happening with very small files. I'll see if I can get a crash dump the next time someone sends me a file via ICQ (which is kinda rare these days ;))

**Comment by dergilb99** [comment] 2017-11-23 12:08
Ok. I just got two screenshots, no problems here. But with larger files it's guaranteed to crash.

**Comment by georgehazan** [comment] 2017-11-23 16:51
@dergilb99 well, it's a network log, not a crash log from the CrashDumper plugin.
https://wiki.miranda-ng.org/index.php?title=Crash_reports

**Comment by uranus** [comment] 2017-11-23 17:17
In my case, when file transfering crash the CrashDumper's log is not created at all.

**Comment by Skeevy** [comment] 2017-11-23 19:15
From my experience only the sender client crashes, the recipient does not. And yes, no crash dump is created when this happens.

**Comment by sagamusix** [comment] 2017-11-23 20:11
As you can read in my description, the recipient can also crash. So, to summarize, the crash conditions are completely random but ICQ file transfer is involved.

**Comment by dergilb99** [comment] 2017-11-30 13:43
> As you can read in my description, the recipient can also crash.

I can confirm this. My Miranda NG crashed as recipient after successfully receiving a 50kb file.

@georgehazan That's all the logs I got. Crash Dumper is installed and running, but no crash log was created.

**Comment by uranus** [comment] 2018-07-09 16:39
![mir-crash](https://user-images.githubusercontent.com/2254465/42463601-47d8f11c-83af-11e8-8d02-7bdcb766312e.png)
Crash is here.

**Closed** 2018-07-09 19:28 UTC
Labels: ICQ, bug, crash

**Comment by georgehazan** [comment] 2018-07-09 19:30
glory, glory, halleluya :)
