### ISSUE TITLE
Add End-to-End Encryption Support for Facebook Messenger Chats in Miranda NG

### ISSUE THREAD

**Issue by winman3000** [miranda-ng/miranda-ng#4805] opened 2024-12-16 08:20 UTC
**Description**
Currently, Miranda NG does not support sending and receiving messages in end-to-end encrypted (E2EE) conversations. Recently, Facebook Messenger has introduced default end-to-end encryption for all chats, which means that once a conversation is migrated to or initiated on the latest Facebook Messenger version, it is fully encrypted and can no longer be viewed or interacted with through Miranda NG. As a result, Miranda NG users are unable to send or receive messages in these encrypted threads, effectively rendering the plugin useless for modern Facebook chats.

To improve user experience and keep Miranda NG compatible with Facebook Messenger, it would be highly beneficial to add support for end-to-end encryption. Implementing E2EE compatibility would ensure that Miranda NG can continue to facilitate secure, private communication without forcing users to switch back and forth between different clients.

**Steps to Reproduce**
1. Ensure both participants in the conversation are using the latest version of Facebook Messenger, which defaults to end-to-end encryption.
1. Start a chat session in the latest Facebook Messenger client.
1. Attempt to continue the conversation using Miranda NG.

**Actual Result**
The conversation is now end-to-end encrypted by default and no longer syncs with Miranda NG. Messages sent from the encrypted Facebook Messenger conversation cannot be read or received within Miranda NG, and messages sent from Miranda NG are not delivered.

**Expected Result**  
Miranda NG should be able to send and receive messages that are end-to-end encrypted, maintaining compatibility and allowing users to continue their secure conversations seamlessly.

**Comment by georgehazan** [comment] 2024-12-19 18:13
duplicate of #4169

**Closed by georgehazan** 2024-12-19 18:13 UTC
Labels: enhancement
