### ISSUE TITLE
Netlib; crash on "netlib_log.cpp (426): Netlib_Log' and 'stdio.h (1408): _vsnprintf"

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#2684] opened 2021-01-08 14:17 UTC
crashlog: http://coraksoft1.narod.ru/temp/miranda/mirandang-20210101-stdio.h-_vsnprintf.7z

Likely cause of the crash plugin: Miranda NG

Exception: Access Violation at address 1003FC2C. Reading from address 00000E30.

Stack Trace:
---------------------------------------------------------------
1003FC2C (ucrtbase 10000000): (filename not available) (0): strnlen
100350AF (ucrtbase 10000000): (filename not available) (0): o_wcsncpy_s
1003577C (ucrtbase 10000000): (filename not available) (0): o_wcsncpy_s
10036DBF (ucrtbase 10000000): (filename not available) (0): _stdio_common_vsprintf
12D22372 (mir_core 12D20000): c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\stdio.h (1408): _vsnprintf
12D304AF (mir_core 12D20000): w:\miranda-build\src\mir_core\src\memory.cpp (225): mir_vsnprintf
12BCC089 (mir_app 12B80000): w:\miranda-build\src\mir_app\src\netlib_log.cpp (426): Netlib_Logf
12BCD1DE (mir_app 12B80000): w:\miranda-build\src\mir_app\src\netlib_openconn.cpp (743): NetlibDoConnect
12BCD441 (mir_app 12B80000): w:\miranda-build\src\mir_app\src\netlib_openconn.cpp (802): NetlibReconnect
12BCA0A6 (mir_app 12B80000): w:\miranda-build\src\mir_app\src\netlib_http.cpp (424): Netlib_SendHttpRequest
12BCB227 (mir_app 12B80000): w:\miranda-build\src\mir_app\src\netlib_http.cpp (862): Netlib_HttpTransaction
7C802455 (kernel32 7C800000): (filename not available) (0): Sleep

**Comment by Corak667** [comment] 2021-01-09 11:34
http://coraksoft1.narod.ru/temp/miranda/mirandang-20201221-stdio.h-_vsnprintf1.7z
Likely cause of the crash plugin: Miranda NG

Exception: Access Violation at address 1003FC07. Reading from address 00000374.

Stack Trace:
---------------------------------------------------------------
1003FC07 (ucrtbase 10000000): (filename not available) (0): strnlen
100350AF (ucrtbase 10000000): (filename not available) (0): o_wcsncpy_s
1003577C (ucrtbase 10000000): (filename not available) (0): o_wcsncpy_s
10036DBF (ucrtbase 10000000): (filename not available) (0): _stdio_common_vsprintf
12D22372 (mir_core 12D20000): c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\stdio.h (1408): _vsnprintf
12D3049F (mir_core 12D20000): w:\miranda-build\src\mir_core\src\memory.cpp (225): mir_vsnprintf
12BCBF19 (mir_app 12B80000): w:\miranda-build\src\mir_app\src\netlib_log.cpp (426): Netlib_Logf
12BCD06E (mir_app 12B80000): w:\miranda-build\src\mir_app\src\netlib_openconn.cpp (743): NetlibDoConnect
12BCD20A (mir_app 12B80000): w:\miranda-build\src\mir_app\src\netlib_openconn.cpp (826): Netlib_OpenConnection
12BCAC53 (mir_app 12B80000): w:\miranda-build\src\mir_app\src\netlib_http.cpp (195): NetlibHttpProcessUrl
12BCAF8C (mir_app 12B80000): w:\miranda-build\src\mir_app\src\netlib_http.cpp (824): Netlib_HttpTransaction
7C802455 (kernel32 7C800000): (filename not available) (0): Sleep
45C7D875 ((module-name not available) 00000000): (filename not available) (0): (function-name not available)

**Comment by georgehazan** [comment] 2021-01-11 09:33
duplicate of #2495

**Closed by georgehazan** 2021-01-11 09:33 UTC
Labels: bug
