### ISSUE TITLE
MSN+SSL: Crash on "Secur32:DecryptMessage", "stdssl: netlibssl.cpp (610): NetlibSslRead" and  "msn_skypeab.cpp (71): CMsnProto::MSN_SKYABRefreshClist"

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#1389] opened 2018-05-26 09:06 UTC
MSN+SSL: Crash on "Secur32:DecryptMessage", "stdssl: netlibssl.cpp (610): NetlibSslRead" and  "msn_skypeab.cpp (71): CMsnProto::MSN_SKYABRefreshClist"

Crashlog: http://coraksoft1.narod.ru/temp/miranda/20180526_msn-ssl-MSN_SKYABRefreshClist-DecryptMessage.zip
```
Likely cause of the crash plugin: Standard SSL Driver

Exception: Access Violation at address 77FEA70E. Reading from address 1D00064C.

Stack Trace:
---------------------------------------------------------------
77FEA70E (Secur32 77FE0000): (filename not available) (0): DecryptMessage
131420CE (stdssl 13140000): w:\miranda-build\src\core\stdssl\src\netlibssl.cpp (610): NetlibSslRead
126AE878 (mir_app 12660000): w:\miranda-build\src\mir_app\src\netlibsock.cpp (77): Netlib_Recv
126A7C0B (mir_app 12660000): w:\miranda-build\src\mir_app\src\netlibhttp.cpp (973): NetlibHttpRecvChunkHeader
126A79F4 (mir_app 12660000): w:\miranda-build\src\mir_app\src\netlibhttp.cpp (1091): NetlibHttpRecv
126A9447 (mir_app 12660000): w:\miranda-build\src\mir_app\src\netlibhttp.cpp (888): Netlib_HttpTransaction
02804BB6 (MSN 027F0000): w:\miranda-build\protocols\msn\src\msn_skypeab.cpp (71): CMsnProto::MSN_SKYABRefreshClist
027F9631 (MSN 027F0000): w:\miranda-build\protocols\msn\src\msn_contact.cpp (261): CMsnProto::MSN_RefreshContactList
0280C856 (MSN 027F0000): w:\miranda-build\protocols\msn\src\msn_threads.cpp (87): CMsnProto::msn_loginThread
128124B0 (mir_core 12800000): w:\miranda-build\src\mir_core\src\threads.cpp (161): forkthreadex_r
7C80B729 (kernel32 7C800000): (filename not available) (0): GetModuleFileNameA

```

**Comment by georgehazan** [comment] 2018-06-01 10:05
duplicate of #1388

**Closed by georgehazan** 2018-06-01 10:05 UTC
