### ISSUE TITLE
Can no longer receive Facebook chat messages

### ISSUE THREAD

**Issue by winman3000** [miranda-ng/miranda-ng#2131] opened 2019-11-20 09:30 UTC
Unfortunately, since yesterday evening, I can not receive any more chat messages from Facebook, even though I see all contacts going online or offline. Yesterday afternoon, everything worked perfectly. Unfortunately I can not give an exact time. I can reproduce this problem on two computers where I use Miranda.

Is this a problem of Facebook or a problem of my account that exists since yesterday evening?

### Miranda NG Version ###
Miranda NG v0.95.11 alpha build #22337 (d98d238287) x64

**Comment by zemiacsik** [comment] 2019-11-24 18:22
It is not only your case, I would say that API maybe changed a bit..

**Comment by dartraiden** [comment] 2019-11-24 18:28
We do not use API. Plugin just parsing HTML.

**Comment by zemiacsik** [comment] 2019-11-24 18:39
In my opinion I would say when you send some request to the application and it send you back some expected response it could also be called API. Maybe some calls coud became obsolete or have changed their structure and as far as I know responses are mostly JSON.

**Comment by ikeblaster** [comment] 2019-11-27 23:30
I think this is an endgame for the protocol in current state. Plugin depends on using long polling for retrieving messages. That's the method facebook used for a long time. However they already switched to different method - websockets (MQTT). A week ago their "pull endpoint" stopped containing messages. It is still working as before, there is just no messages in returned data. I don't see anything we can do here. It would be nice if there was some switch, which would enable it again, but I don't think there is.

Source: packet sniffing communication between miranda and FB (using Fiddler)

**Comment by newsjunkie247** [comment] 2019-11-28 06:42
I still get pop-ups on the newest version of Miranda when I do a new launch of opening the program, so the process doesn't seem to be completely broken. Shouldn't there be a way to initiate that process during the run of the program as well?

**Comment by ikeblaster** [comment] 2019-11-28 09:12
Loading unread messages is a different process and is probably done just once, when you switch to online state. It uses different endpoint. It's not reasonable to use this for real-time communication, there would be huge delays. Same applies for "history synchronization" (it's an option in plugin settings), that also works.

**Comment by georgehazan** [comment] 2019-11-29 18:18
@ikeblaster which concrete call now returns the void dataset? maybe we can google it by its url, I doubt that we are the only people who faced this problem

**Comment by ikeblaster** [comment] 2019-11-29 20:07
@georgehazan Miranda polls this URL. Leading digit is irelevant.
```
https://6-edge-chat.facebook.com/pull?channel=p_100004451683377&seq=1&partition=-2&clientid=a87fbddb&cb=lk4h&idle=0&qp=y&pws=fresh&isq=487632&msgs_recv=1&cap=8&uid=100004451683377&viewer_uid=100004451683377&sticky_token=1234&sticky_pool=rash0c01_chatproxy-regional&state=active
```

It waits approx. 50 seconds, then returns this every time:
```
for (;;); {"t":"heartbeat"}
```

Previously it returned as soon as a message was received and the message was part of the response. If there was no message, than the behaviour would be the same as is now (=50 sec wait, then heartbeat response).

---

When I open FB messenger in browser it uses the same pull endpoint and it behaves the same. I don't know whether it contained messages earlier. I would guess that it did not, since messages are transfered via websocket (URL `wss://edge-chat.facebook.com/chat?region=lla&sid=xxxxxxxxxxxxxx` [x are digits]).

---

Here they have the same problem. There are some forks/PR with MQTT/WS implementation. It could be useful for us.

https://github.com/Schmavery/facebook-chat-api/issues/763

**Comment by georgehazan** [comment] 2019-12-06 19:17
@ikeblaster the problem is that all existing applications that use MQTT are oriented on the very old protocol version, kinda 1.2 or 1.3 (current one is 3.3 / 3,4), so that code can't be imported directly.

**Comment by georgehazan** [comment] 2019-12-06 19:18
I've committed a skeleton of MQTT project for Facebook into our git, but it can't even log in

**Comment by ikeblaster** [comment] 2019-12-06 19:23
@georgehazan From my point of view version 1.2 is better than nothing. We can work from there, compare different implementation (nodejs library can log in, I tried that) and in worst case try to reverse engineer the protocol the current messenger.com uses.

It's this, right? https://github.com/miranda-ng/miranda-ng/tree/master/protocols/Facebook/src

I will try to look at it on the weekend if I have time. For me this was the worst part, since I don't have the whole picture of miranda code and how things (like new libraries) should be connected together. But keep you hopes low. :)

**Comment by ikeblaster** [comment] 2019-12-06 19:50
From what I remember - that nodejs library doesn't rely on MQTT only. In fact it didn't use MQTT at all and those forks added it only to fix receiving messages. So maybe we just need a hybrid between our old protocol (which can log in) and MQTT part purely for messaging. There will have to be some mechanism of generating MQTT authentication ticket or something like that (just sounds logical to me, it could be completely different).

**Comment by ikeblaster** [comment] 2019-12-08 20:20
@georgehazan Just letting you know, if interested. :)

So I managed to get an access token (via b-api.facebook.com/method/auth.login, without oauth+custom FB app [I think it still wouldn't work for our purpose]). [bitlbee-facebook](https://github.com/bitlbee/bitlbee-facebook/blob/c612d255ec7c2699aef70b6eab10920a914c313d/facebook/facebook-api.c#L2284) uses exactly this, so it should be ok (at least for now).

And that's the only succesful thing I was able to achieve. MQTT connection itself for some reason fails. It sends CONNECT message (type 0001) and FB should reply with CONNACK message (type 0010). But it also responds with message 0001. Or at least I think it does (first 4 bits should be message type). Here is netlog.

```
[2:24:15 0588] [Facebook_1] (1432) Connected to mqtt.facebook.com:443
[2:24:15 0588] [Facebook_1] Deflate: Z_OK
[2:24:15 0588] [Facebook_1] (06CF7478:1432) Data sent
00000000: 10 F5 02 00-06 4D 51 54-54 6F 54 03-CA 00 3C 78  .ő...MQTToT.Ę.<x
00000010: DA 0C CE 4D-6A DB 40 00-05 60 27 D0-03 18 62 E3  Ú.ÎMjŰ@..`'Đ..bă
00000020: 03 74 93 85-7E 66 46 63-8F 68 36 A3-91 64 39 B5  .t“…~fFcŹh6Ł‘d9µ
00000030: 95 58 6A AC-78 4A 08 B2-A4 31 8E 6C-8D A4 44 35  •Xj¬xJ.˛¤1ŽlŤ¤D5
00000040: E8 06 DD F5-0A 85 6C 53-68 D7 81 6E-BB E9 09 7A  č.Ýő.…lSh×n»é.z
00000050: 8B EE 0B 15-6F F3 F8 E0-C1 1B 9D 55-EB B8 D2 A1  ‹î..oóřŕÁ.ťUë¸Ňˇ
00000060: 59 59 31 3D-7A 8B C8 CC-1B DC 5E 0C-BF FC 7D FD  YY1=z‹ČĚ.Ü^.żü}ý
00000070: F6 F2 53 19-45 1F 5D 8B-FA DA 55 9D-C4 0A 2D D2  öňS.E.]‹úÚUťÄ.-Ň
00000080: 5A EE D2 77-9D AC 34 60-42 55 EF 82-80 0A 74 D0  ZîŇwť¬4`BUď‚€.tĐ
00000090: D9 B5 AF 25-F2 A0 8A 38-C9 36 52 E6-AA EC 26 1D  ŮµŻ%ň Š8É6RćŞě&.
000000A0: CF 99 96 15-F7 37 61 57-AD 95 86 21-20 70 3C 86  Ď™–.÷7aW­•†! p<†
000000B0: 77 43 75 68-0C 4E FB FD-D1 5B 82 63-42 80 21 14  wCuh.NűýŃ[‚cB€!.
000000C0: 61 26 40 31-30 C2 0A C9-80 50 8C 09-C4 9B 6C 42  a&@10Â.É€PŚ.Ä›lB
000000D0: 74 3C 49 FA-83 D3 41 6F-F8 FD EB EF-D7 CF 3F FE  t<IúÓAořýëď×Ď?ţ
000000E0: 3D FF 39 39-7F D3 1B FD-3A 71 28 B5-25 F8 60 73  =˙99Ó.ý:q(µ%ř`s
000000F0: D6 34 A4 7B-39 5B 6E 9C-56 38 B3 68-EF 16 9F 74  Ö4¤{9[nśV8łhď.źt
00000100: 56 1E 3D C8-59 30 95 F3-79 CB 69 CA-69 E9 EC 93  V.=ČY0•óyËiĘiéě“
00000110: A6 10 BB DD-3C 31 71 D8-94 65 8D C6-91 5D EF D1  ¦.»Ý<1qŘ”eŤĆ‘]ďŃ
00000120: A5 30 88 27-16 1E 32 8B-E9 36 B8 0D-23 CB 29 24  Ą0'..2‹é6¸.#Ë)$
00000130: 67 EF D7 4E-90 2F 6A 50-3D DE 6C 11-A7 30 F0 ED  gď×N/jP=Ţl.§0đí
00000140: 27 BD 04 32-DF 72 7A 1D-3E 2E A7 A9-8B 96 FA C3  '˝.2ßrz.>.§©‹–úĂ
00000150: A4 DD 59 50-1C 82 32 D5-EB D6 88 28-E1 6C DC 96  ¤ÝYP.‚2ŐëÖ(álÜ–
00000160: D4 E5 EC 69-95 57 9C 49-CC 0E 28 8F-66 57 CB 45  Ôĺěi•WśIĚ.(ŹfWËE
00000170: ED 5E 86 C8-03 7E E6 26-56 88 C5 D1-7F F0 D7 DC  í^†Č.~ć&VĹŃđ×Ü
00000180: EE FD 07 00-00 FF FF                             îý...˙˙
[2:24:15 0588] [Facebook_1] (06CF7478:1432) Data received
00000000: 15 03 03 00-02 02 32                             ......2
[2:24:15 0588] [Facebook_1] Connection closed gracefully
[2:24:15 0588] [Facebook_1] exiting ServerThread
```

I checked that all the variables inside our connect message are present (m_szClientID, m_uid, m_szDeviceID, m_iMqttId, m_szAuthToken). Next step would be to compare it with bitlbee-facebook, where it differs. Or there is another JS library which is just port of bitlbee-facebook. That could be easier to debug. 

I didn't publish it anywhere (I just hardcoded my credentials), let me know if you want it.

**Comment by ikeblaster** [comment] 2019-12-15 02:46
@georgehazan (or anyone else interested, sorry to tag just you) 

I have finally managed MQTT to succesfully connect (response is `20 02 00 00`, same as pidgin gets) and also using graphql endpoint is working. Now we need to implement:

1) MQTT communication itself - registering to events and handling received messages.
2) Loading data from graph API, like buddies (maybe just during login, to load new contacts - status changes might be accessible over MQTT [not sure]).

My question stays - should I clean up the code and publish it, or just continue in my work?

This can take me ages, I have almost zero knowledge how contacts and messages in miranda work. I am able to dig around FB protocols/data retrieving, but handing the data into miranda core is difficult to me.

---

For others - I guess we can finally be slightly optimistic. Baby steps. :) By the way I was never "blocked" by FB (forced to change my password, etc.) during testing pidgin (also... it's is a horrible stepdown from fine-tuned miranda). So another benefit confirmed.

**Comment by georgehazan** [comment] 2019-12-15 11:07
@ikeblaster wow, great news
I can add you as a committer to our repo, so you could manage new version of FB proto, thus allowing us to remove the old plugin completely

**Comment by georgehazan** [comment] 2019-12-16 17:25
@ikeblaster feel free to patch /miranda-ng/protocols/Facebook/src anyhow to make it connecting okay, then I'll help you. I've got stuck on this point. Also, if you want, I can commt libmosquitto into Miranda

**Comment by ikeblaster** [comment] 2019-12-16 17:29
@georgehazan I will commit the changes later today. Sorry for the delays, I don't have much time these days (deadlines are close).

**Comment by georgehazan** [comment] 2019-12-17 10:50
@ikeblaster same story :-)
I saw your commits 👍 will try to look at them a bit later

**Closed** 2020-01-26 18:04 UTC
Labels: Facebook, bug
