### ISSUE TITLE
History++ doesn't show all characters

### ISSUE THREAD

**Issue by Tragen** [miranda-ng/miranda-ng#1415] opened 2018-06-10 10:00 UTC
In the chat log, I can see the emoji and everything is fine.
Like 😂
In History++ it looks like 
![image](https://user-images.githubusercontent.com/1700241/41200497-c847aec2-6ca5-11e8-890a-b6b7af447d5c.png)

What can I do that it is shown correctly? When I copy it and paste it in Firefox, the correct character is drawn, so it is saved correctly in the history.

**Comment by Tragen** [comment] 2018-06-10 10:01
Same system info like in https://github.com/miranda-ng/miranda-ng/issues/1413

**Comment by dartraiden** [comment] 2018-06-11 20:27
Duplicate of #840

**Closed by dartraiden** 2018-06-11 20:27 UTC
