### ISSUE TITLE
Core: crash in "stdio.h (1408): _vsnprintf" and "netlib_log.cpp (426): Netlib_Logf"

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#2877] opened 2021-05-08 14:42 UTC
Crashlog: 
[mirandang-crash-20210407-Netlib_Logf.zip](https://github.com/miranda-ng/miranda-ng/files/6447542/mirandang-crash-20210407-Netlib_Logf.zip)

```
Likely cause of the crash plugin: Miranda NG

Exception: Access Violation at address 1003FC07. Reading from address 00460038.

Stack Trace:
---------------------------------------------------------------
1003FC07 (ucrtbase 10000000): (filename not available) (0): strnlen
100350AF (ucrtbase 10000000): (filename not available) (0): o_wcsncpy_s
1003577C (ucrtbase 10000000): (filename not available) (0): o_wcsncpy_s
10036DBF (ucrtbase 10000000): (filename not available) (0): _stdio_common_vsprintf
12CC2372 (mir_core 12CC0000): c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\stdio.h (1408): _vsnprintf
12CD08D7 (mir_core 12CC0000): w:\miranda-build\src\mir_core\src\memory.cpp (225): mir_vsnprintf
12B4D876 (mir_app 12B00000): w:\miranda-build\src\mir_app\src\netlib_log.cpp (426): Netlib_Logf
12B4E9CB (mir_app 12B00000): w:\miranda-build\src\mir_app\src\netlib_openconn.cpp (743): NetlibDoConnect
12B4EB67 (mir_app 12B00000): w:\miranda-build\src\mir_app\src\netlib_openconn.cpp (826): Netlib_OpenConnection
12B4C5B0 (mir_app 12B00000): w:\miranda-build\src\mir_app\src\netlib_http.cpp (195): NetlibHttpProcessUrl
12B4C8E9 (mir_app 12B00000): w:\miranda-build\src\mir_app\src\netlib_http.cpp (824): Netlib_HttpTransaction
7C802576 (kernel32 7C800000): (filename not available) (0): Sleep
45C7D875 ((module-name not available) 00000000): (filename not available) (0): (function-name not available)
```

**Comment by georgehazan** [comment] 2021-05-13 18:48
duplicate of #2495

**Closed by georgehazan** 2021-05-13 18:48 UTC
Labels: bug, core, crash
