### ISSUE TITLE
Netlib SSL + VK: crash on "netlibssl.cpp (525): NetlibSslReadSetResult", "netlibsock.cpp (77): Netlib_Recv" and "vk_pollserver.cpp (211): CVkProto::PollServer"

### ISSUE THREAD

**Issue by Corak667** [miranda-ng/miranda-ng#881] opened 2017-08-08 15:46 UTC
```
Likely cause of the crash plugin: Standard SSL Driver

Exception: Access Violation at address 72E71ED7. Reading from address 00610074.

Stack Trace:
---------------------------------------------------------------
72E71ED7 (MSVCR100 72E70000): (filename not available) (0): memcpy
13181A90 (stdssl 13180000): c:\sources\miranda_ng_compilation\src\core\stdssl\src\netlibssl.cpp (525): NetlibSslReadSetResult
13182442 (stdssl 13180000): c:\sources\miranda_ng_compilation\src\core\stdssl\src\netlibssl.cpp (572): NetlibSslRead
1243F7CA (mir_app 12420000): c:\sources\miranda_ng_compilation\src\mir_app\src\netlibsock.cpp (77): Netlib_Recv
12444107 (mir_app 12420000): c:\sources\miranda_ng_compilation\src\mir_app\src\netlibhttp.cpp (106): RecvWithTimeoutTime
12444787 (mir_app 12420000): c:\sources\miranda_ng_compilation\src\mir_app\src\netlibhttp.cpp (1064): NetlibHttpRecv
12444DB9 (mir_app 12420000): c:\sources\miranda_ng_compilation\src\mir_app\src\netlibhttp.cpp (889): Netlib_HttpTransaction
1726A01C (VKontakte 17260000): c:\sources\miranda_ng_compilation\protocols\vkontakte\src\vk_pollserver.cpp (211): CVkProto::PollServer
1726A243 (VKontakte 17260000): c:\sources\miranda_ng_compilation\protocols\vkontakte\src\vk_pollserver.cpp (266): CVkProto::PollingThread
125C7F67 (mir_core 125C0000): c:\sources\miranda_ng_compilation\src\mir_core\src\threads.cpp (159): forkthreadex_r
758C338A (kernel32 758B0000): (filename not available) (0): BaseThreadInitThunk
77D99F72 (ntdll 77D60000): (filename not available) (0): RtlInitializeExceptionChain
77D99F45 (ntdll 77D60000): (filename not available) (0): RtlInitializeExceptionChain
125C7F3E (mir_core 125C0000): c:\sources\miranda_ng_compilation\src\mir_core\src\threads.cpp (284): Thread_Wait
0D77FDE8 ((module-name not available) 00000000): (filename not available) (0): (function-name not available)

```
log:
[mir_20170808_ssl-NetlibSslReadSetResult_vk-PollServer.zip](https://github.com/miranda-ng/miranda-ng/files/1232456/mir_20170808_ssl-NetlibSslReadSetResult_vk-PollServer.zip)

**Comment by georgehazan** [comment] 2017-09-25 10:38
closed as duplicate of #930

**Closed by georgehazan** 2017-09-25 10:38 UTC
Labels: bug, crash, VKontakte
