### ISSUE TITLE
facebook contacts always show as offline 

### ISSUE THREAD

**Issue by slanovani** [miranda-ng/miranda-ng#1987] opened 2019-06-16 06:34 UTC
hi, 

i'm writing to you in order to report a bug in latest version of miranda ng. 

Thing is that facebook contacts are always showing as offline, no matter if they're acctually online. 

it's happening with absolutely all of contacts, so i would not think that they're putting themselves as invisible or anything like that. I already checked my connections and I'm having no isue, because as I said, contacts write to me from other machines and even from their phones. 

hope to hear from you soon!

Regards, 

Slann. 
![Captura de pantalla (1)](https://user-images.githubusercontent.com/15083215/59560383-c311ae80-8fd6-11e9-973b-6f6df188eac4.png)
![Captura de pantalla (2)](https://user-images.githubusercontent.com/15083215/59560384-c311ae80-8fd6-11e9-8504-5620abc172fe.png)
![Captura de pantalla (3)](https://user-images.githubusercontent.com/15083215/59560385-c311ae80-8fd6-11e9-8ed9-47d8ccba3969.png)

**Comment by dartraiden** [comment] 2019-06-16 09:32
Duplicate of #1980

**Closed by dartraiden** 2019-06-16 09:32 UTC
