### ISSUE TITLE
clist: feature request - mass selection / moving / deleting of contacts by ctrl/shift and drag'n'drop

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#451] opened 2016-10-21 20:00 UTC
**Reported by Corak on 20 Sep 2015 15:44 UTC**
Feature request to deal with contacts as "files" in most GUI OS standards:
1. Linear mass selection of contacts by - selecting start point (where begin selection), then holding SHIFT and clicking left mouse button / moving cursor up or down to the lastest selection point.
- Also single selection by holding CTRL and clicking on them with left mouse button
- Ability to move such group of contacts to folders by drag'n'droppin them.
- Ability to delete such contacts on DEL button or Right mouse click (and NEW menu with some options for group of contacts)
- Special option - asking about "Do you want to delete %n contacts". Such option I think must be disableable and placed where is already "single contact delete question"

**Comment by georgehazan** [comment] 2016-10-21 20:00
**Modified by Corak on 20 Sep 2015 15:47 UTC**

**Comment by georgehazan** [comment] 2016-10-21 20:00
**Modified by Corak on 20 Sep 2015 15:53 UTC**

**Comment by georgehazan** [comment] 2016-10-21 20:00
**Modified by Corak on 20 Sep 2015 15:54 UTC**

**Comment by dartraiden** [comment] 2016-12-13 15:57
Duplicate of #436

**Closed by dartraiden** 2016-12-13 15:57 UTC
Labels: contact list, enhancement, major
