### ISSUE TITLE
Provide secure HTTPS downloads of Miranda-ng.

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#374] opened 2016-10-19 16:42 UTC
**Reported by kyhwana on 31 Mar 2015 12:11 UTC**
Miranda-ng binaries are not available via HTTPS.
Users should be directed to https:// download links from a https:// secured page of miranda-ng to prevent inflight tampering of miranda-ng binaries.

This is possible in various scenario's, including compromise of user's modem/routers ( http://aralabs.com/blog/2015/03/25/ad-fraud-malware-hijacks-router-dns-injects-ads-via-google-analytics/ ), BGP hijacking ( http://www.internetsociety.org/deploy360/blog/2014/08/bgp-hijacker-steals-bitcoins/ ) , downloading via tor (https://www.leviathansecurity.com/blog/the-case-of-the-modified-binaries/ ) , Country wide filters ( http://www.netresec.com/?month=2015-03&page=Blog&post=China%27s-Man-on-the-Side-Attack-on-GitHub ) or Nation State actors. ( https://www.techdirt.com/articles/20130910/10470024468/flying-pig-nsa-is-running-man-middle-attacks-imitating-googles-servers.shtml )

There are already tools out there to do this: https://github.com/secretsquirrel/BDFProxy

Startcom offers 1 year free SSL certificates: https://www.startssl.com/?app=1
Wosign offers free 2 year SSL certificates: https://www.ohling.org/blog/2015/02/wosign-free-2y-ssl-certificate.html
Both of these work in all major browsers.
Hopefully mid this year, Letsencrypt https://letsencrypt.org/ will hopefully be done, giving out free automated certificates.

wosign will issue up to 100 SANs (Subject Alt Names) per certificate, allowing you to put trac/wiki/www/etc subdomains under the same certificate.

Mozilla has a server configuration guide for securely configuring your server side TLS: https://wiki.mozilla.org/Security/Server_Side_TLS

https://www.ssllabs.com/ssltest/index.html SSL Labs server test can be used to test HTTPS server configurations live.

Once up and running and you're confident in your config, you should also apply HSTS, which will disallow users from clicking through any certificate warnings: https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security

Performance: http://moz.com/blog/enabling-https-without-sacrificing-web-performance (Ensuring to follow the mozilla server side TLS guide still. HTTPS adds negligable performance impacts these days, especially if you enable ECC based ciphersuites: https://istlsfastyet.com/ )

While GPG signing binaries and providing hashsums of binaries is also useful, hardly any users bother and providing hashsums over http is pointless as an attacker can also modifiy these. Providing HTTPS downloads by default will protect all users, almost all of the time.

**Comment by LittleVulpix** [comment] 2017-02-22 13:58
Can be closed as a duplicate of #697 , letsencrypt and its use recommended in the said ticket as well.

**Comment by dartraiden** [comment] 2017-02-22 14:24
Duplicate of #697.

**Closed by dartraiden** 2017-02-22 14:24 UTC
Labels: bug, core, major
