### ISSUE TITLE
skype does not login

### ISSUE THREAD

**Issue by ivan1282ka** [miranda-ng/miranda-ng#2951] opened 2021-08-11 10:48 UTC
Hi! Skype refuses to log in . What i can do? 
Здравствуйте. Скайп не хочет войти. Что можно сделать? 

Thanks. 
Best regards. 
Спасибо

here the log:
Вот и справка: 

[13:44:11 ч. 53EC] [SKYPE_3] CSkypeProto::SetStatus: changing status from 40071 to 40072
[13:44:11 ч. 21E8] [SKYPE_3] Send request to https://login.live.com/login.srf?wa=wsignin1.0&wp=MBI_SSL&wreply=https%3A%2F%2Flw.skype.com%2Flogin%2Foauth%2Fproxy%3Fsite_name%3Dlw.skype.com&cobrandid=90010
[13:44:11 ч. 21E8] [SKYPE_3] Connection request to login.live.com:443 (Flags 11)....
[13:44:11 ч. 21E8] [SKYPE_3] (037CE720) Connecting to server login.live.com:443....
[13:44:11 ч. 21E8] [SKYPE_3] (037CE720) Connecting to ip 40.126.31.2:443 ....
[13:44:11 ч. 21E8] [SKYPE_3] (1760) Connected to login.live.com:443
[13:44:11 ч. 21E8] [SKYPE_3] (1760 login.live.com) Starting SSL/TLS negotiation
[13:44:16 ч. 21E8] [SKYPE_3] (1760 login.live.com) SSL/TLS negotiation successful
[13:44:16 ч. 21E8] [SKYPE_3] (037CE720:1760) Connection closed internal
[13:44:16 ч. 21E8] [SKYPE_3] (037CE720:4294967295) Connection closed
[13:44:16 ч. 21E8] [SKYPE_3] Send request to https://login.live.com/ppsecure/post.srf?wa=wsignin1.0&wp=MBI_SSL&wreply=https%3A%2F%2Flw.skype.com%2Flogin%2Foauth%2Fproxy%3Fsite_name%3Dlw.skype.com&cobrandid=90010
[13:44:16 ч. 21E8] [SKYPE_3] Connection request to login.live.com:443 (Flags 11)....
[13:44:16 ч. 21E8] [SKYPE_3] (037CE720) Connecting to server login.live.com:443....
[13:44:16 ч. 21E8] [SKYPE_3] (037CE720) Connecting to ip 40.126.31.2:443 ....
[13:44:16 ч. 21E8] [SKYPE_3] (1760) Connected to login.live.com:443
[13:44:16 ч. 21E8] [SKYPE_3] (1760 login.live.com) Starting SSL/TLS negotiation
[13:44:16 ч. 21E8] [SKYPE_3] (1760 login.live.com) SSL/TLS negotiation successful
[13:44:17 ч. 21E8] [SKYPE_3] (037CE720:1760) Connection closed internal
[13:44:17 ч. 21E8] [SKYPE_3] (037CE720:4294967295) Connection closed
[13:44:17 ч. 21E8] [SKYPE_3] Send request to https://login.live.com/ppsecure/post.srf?wa=wsignin1.0&wp=MBI_SSL&wreply=https%3A%2F%2Flw.skype.com%2Flogin%2Foauth%2Fproxy%3Fsite_name%3Dlw.skype.com&cobrandid=90010
[13:44:17 ч. 21E8] [SKYPE_3] Connection request to login.live.com:443 (Flags 11)....
[13:44:17 ч. 21E8] [SKYPE_3] (037CE880) Connecting to server login.live.com:443....
[13:44:17 ч. 21E8] [SKYPE_3] (037CE880) Connecting to ip 40.126.31.2:443 ....
[13:44:17 ч. 21E8] [SKYPE_3] (2380) Connected to login.live.com:443
[13:44:17 ч. 21E8] [SKYPE_3] (2380 login.live.com) Starting SSL/TLS negotiation
[13:44:17 ч. 21E8] [SKYPE_3] (2380 login.live.com) SSL/TLS negotiation successful
[13:44:17 ч. 21E8] [SKYPE_3] (037CE880:2380) Connection closed internal
[13:44:17 ч. 21E8] [SKYPE_3] (037CE880:4294967295) Connection closed
[13:44:17 ч. 21E8] [SKYPE_3] CSkypeProto::SetStatus: changing status from 1 to 40071

[spoiler=VersionInfo][quote]CPU: Intel(R) Core(TM)2 Quad CPU Q9400 @ 2.66GHz [x86 Family 6 Model 23 Stepping 10] [DEP Enabled] [4 CPUs]
Installed RAM: 8176 MBytes
Microsoft Windows 7 Ultimate Edition, 32-bit Service Pack 1 (build 7601)
Internet Explorer: 9.11.9600.18697 (build 99600)
Administrator privileges: Yes
OS Languages: (UI | Locale (User/System)) : Bulgarian/Bulgarian | Bulgarian/Bulgarian
Free disk space on Miranda partition: 66202 MBytes

Miranda NG Version: 0.96.1 alpha build #24171 (5bd2d22ff7)
Build time: 10 Aug 2021 11:10:28
Profile: C:\Users\user\Desktop\mirandang-ne\profiles\profile090108\profile090108.dat
Database driver: SQLite database driver
Profile size: 8933376 Bytes
Profile creation date: 1 Jul 2021 1:24:50
Language pack: No language pack installed
Service Mode: No

[b]Active Plugins (57):[/b]
¤ AddContactPlus.dll v.[b]0.9.9.2[/b] [7 Aug 2021 2:01:50] - Add contact+ 
¤ AuthState.dll v.[b]0.0.2.2[/b] [7 Aug 2021 2:01:26] - Authorization state 
¤ AVS.dll v.[b]0.98.1.3[/b] [7 Aug 2021 2:01:28] - Avatar service 
¤ BuddyExpectator.dll v.[b]0.1.2.3[/b] [7 Aug 2021 2:01:26] - Buddy expectator 
¤ BuddyPounce.dll v.[b]0.3.3.0[/b] [7 Aug 2021 2:02:28] - Buddy pounce 
¤ Clist_nicer.dll v.[b]0.9.3.2[/b] [7 Aug 2021 2:01:40] - Clist nicer 
¤ Cln_skinedit.dll v.[b]0.0.0.4[/b] [7 Aug 2021 2:01:28] - Skin editor for Clist nicer 
¤ CloudFile.dll v.[b]0.11.0.6[/b] [7 Aug 2021 2:03:12] - CloudFile 
¤ Contacts.dll v.[b]1.6.0.0[/b] [7 Aug 2021 2:01:34] - Send/receive contacts 
¤ CrashDumper.dll v.[b]0.1.0.4[/b] [7 Aug 2021 2:02:06] - Crash dumper 
¤ CryptoPP.dll v.[b]1.0.4.8[/b] [7 Aug 2021 2:03:24] - Crypto++ 
¤ Db_autobackups.dll v.[b]0.1.0.5[/b] [10 Aug 2021 11:10:54] - Db autobackuper 
¤ DbChecker.dll v.[b]0.95.13.2[/b] [10 Aug 2021 11:12:48] - Database checker 
¤ DbEditorPP.dll v.[b]4.1.0.2[/b] [7 Aug 2021 2:02:08] - Database editor++ 
¤ Dbx_mdbx.dll v.[b]0.95.9.1[/b] [10 Aug 2021 11:12:50] - Miranda NG MDBX database driver 
¤ Dbx_mmap.dll v.[b]0.95.8.1[/b] [7 Aug 2021 2:01:26] - Miranda NG mmap database driver 
¤ Dbx_sqlite.dll v.[b]0.96.1.2[/b] [10 Aug 2021 11:12:46] - Miranda NG SQLite database driver 
¤ Discord.dll v.[b]0.6.2.10[/b] [7 Aug 2021 2:02:54] - Discord protocol 
¤ Dummy.dll v.[b]0.2.0.0[/b] [10 Aug 2021 11:12:14] - Dummy protocol 
¤ Facebook.dll v.[b]0.1.0.11[/b] [7 Aug 2021 2:03:14] - Facebook 
¤ FileAsMessage.dll v.[b]0.1.0.1[/b] [7 Aug 2021 2:03:00] - File as message 
¤ Fingerprint.dll v.[b]0.2.0.1[/b] [7 Aug 2021 2:02:18] - Fingerprint NG 
¤ Flags.dll v.[b]0.1.0.4[/b] [7 Aug 2021 2:01:30] - Country flags 
¤ FltContacts.dll v.[b]0.7.0.5[/b] [7 Aug 2021 2:01:36] - Floating contacts 
¤ FTPFile.dll v.[b]0.6.0.6[/b] [7 Aug 2021 2:03:48] - FTP File YM 
¤ GG.dll v.[b]0.95.11.1[/b] [7 Aug 2021 2:01:56] - Gadu-Gadu protocol 
¤ historypp.dll v.[b]1.5.1.5[/b] [7 Aug 2021 2:03:58] - History++ 
¤ ICQ.dll v.[b]0.96.1.4[/b] [10 Aug 2021 11:12:48] - ICQ-WIM protocol 
¤ Import.dll v.[b]0.95.11.1[/b] [10 Aug 2021 11:11:40] - Import contacts and messages 
¤ Jabber.dll v.[b]0.95.11.1[/b] [7 Aug 2021 2:02:20] - Jabber protocol 
¤ MenuEx.dll v.[b]1.3.2.0[/b] [7 Aug 2021 2:01:38] - Menu item ext 
¤ MessageState.dll v.[b]0.1.0.2[/b] [7 Aug 2021 2:02:48] - Message state 
¤ MyDetails.dll v.[b]0.1.0.1[/b] [7 Aug 2021 2:02:12] - My details 
¤ NewXstatusNotify.dll v.[b]1.4.0.12[/b] [7 Aug 2021 2:01:40] - xStatus notify 
¤ Omegle.dll v.[b]0.1.3.3[/b] [7 Aug 2021 2:02:00] - Omegle protocol 
¤ OpenFolder.dll v.[b]1.1.0.0[/b] [7 Aug 2021 2:02:06] - Open Miranda folder 
¤ PluginUpdater.dll v.[b]0.2.0.12[/b] [7 Aug 2021 2:02:12] - Plugin updater 
¤ PManagerEx.dll v.[b]0.0.0.5[/b] [7 Aug 2021 2:02:10] - Miranda NG profile changer 
¤ PopupPlus.dll v.[b]2.1.1.17[/b] [7 Aug 2021 2:02:06] - Popup plus 
¤ Restart.dll v.[b]0.0.6.0[/b] [7 Aug 2021 2:02:10] - Restart 
¤ Sametime.dll v.[b]0.7.0.5[/b] [7 Aug 2021 2:03:44] - Sametime protocol 
¤ SecureIM.dll v.[b]1.0.12.6[/b] [7 Aug 2021 2:01:52] - SecureIM 
¤ SeenPlugin.dll v.[b]5.0.5.6[/b] [7 Aug 2021 2:01:44] - Last seen 
¤ SkypeWeb.dll v.[b]0.95.13.3[/b] [7 Aug 2021 2:02:54] - Skype protocol (Web) 
¤ SmileyAdd.dll v.[b]0.3.2.1[/b] [7 Aug 2021 2:01:56] - SmileyAdd 
¤ SpellChecker.dll v.[b]0.2.6.6[/b] [7 Aug 2021 2:03:08] - Spell checker 
¤ StatusManager.dll v.[b]1.2.0.6[/b] [7 Aug 2021 2:02:56] - Status manager 
¤ Steam.dll v.[b]0.95.12.2[/b] [7 Aug 2021 2:03:00] - Steam protocol 
¤ Tipper.dll v.[b]2.1.0.7[/b] [7 Aug 2021 2:01:50] - Tipper 
¤ TooltipNotify.dll v.[b]0.7.0.1[/b] [7 Aug 2021 2:01:46] - Tooltip notify 
¤ TopToolBar.dll v.[b]0.8.0.5[/b] [7 Aug 2021 2:01:58] - TopToolBar 
¤ Tox.dll v.[b]0.11.3.2[/b] [7 Aug 2021 2:03:42] - Tox protocol 
¤ UInfoEx.dll v.[b]0.9.0.1[/b] [7 Aug 2021 2:02:04] - User info ext 
¤ WhenWasIt.dll v.[b]0.3.3.5[/b] [7 Aug 2021 2:01:50] - Birthday reminder 
¤ WhoUsesMyFiles.dll v.[b]0.1.0.4[/b] [7 Aug 2021 2:02:04] - Who Use My Files 
¤ YAMN.dll v.[b]0.1.2.6[/b] [7 Aug 2021 2:02:20] - Mail Notifier 
¤ ZeroNotify.dll v.[b]0.1.0.1[/b] [7 Aug 2021 2:01:48] - Zero notifications 

[b]Unloadable Plugins (26):[/b]
¤ AutoLoadAvatars.dll v.[b]0.0.0.0[/b] [21 Oct 2004 11:05:16] - <unknown> 

¤ Birthday.dll v.[b]0.0.0.0[/b] [13 May 2004 22:12:24] - <unknown> 

¤ changeinfo.dll v.[b]0.0.0.0[/b] [16 Jun 2005 14:39:02] - <unknown> 

¤ contactvisibility.dll v.[b]0.0.0.0[/b] [12 May 2003 22:34:38] - <unknown> 

¤ CopyIP.dll v.[b]0.0.0.0[/b] [16 Feb 2002 12:39:38] - <unknown> 

¤ IcoLib.dll v.[b]0.0.0.0[/b] [25 Oct 2006 18:11:38] - <unknown> 

¤ ImgLib.dll v.[b]0.0.0.0[/b] [19 Oct 2004 14:11:28] - <unknown> 

¤ JGmail.dll v.[b]0.0.0.0[/b] [5 Jun 2009 18:00:16] - <unknown> 

¤ loadavatars.dll v.[b]0.0.0.0[/b] [1 Aug 2006 16:31:18] - <unknown> 

¤ mSecure.dll v.[b]0.0.0.0[/b] [17 Sep 2003 1:35:46] - <unknown> 

¤ msn_accountsetup.dll v.[b]0.0.0.0[/b] [23 Jan 2005 13:50:00] - <unknown> 

¤ mtextcontrolA.dll v.[b]0.0.0.0[/b] [6 Jan 2007 3:14:58] - <unknown> 

¤ mVisibility.dll v.[b]0.0.0.0[/b] [14 Mar 2005 15:53:44] - <unknown> 

¤ Notifier.dll v.[b]0.0.0.0[/b] [24 Nov 2005 22:59:18] - <unknown> 

¤ pastelweather.dll v.[b]0.0.0.0[/b] [27 Nov 2002 19:00:20] - <unknown> 

¤ pop3.dll v.[b]0.0.0.0[/b] [21 Aug 2002 16:21:04] - <unknown> 

¤ proto_JGMAIL.dll v.[b]0.0.0.0[/b] [26 Feb 2007 12:11:16] - <unknown> 

¤ realreconnect.dll v.[b]0.0.0.0[/b] [26 Dec 2005 15:08:46] - <unknown> 

¤ SecureIM_icons.dll v.[b]0.0.0.0[/b] [7 May 2009 13:41:54] - <unknown> 

¤ smtpsimple.dll v.[b]0.0.0.0[/b] [12 Aug 2003 0:49:10] - <unknown> 

¤ TypingNotify.dll v.[b]0.0.0.0[/b] [5 Jul 2004 23:39:30] - <unknown> 

¤ updater.dll v.[b]0.0.0.0[/b] [19 Mar 2011 23:31:02] - <unknown> 

¤ Wassup.dll v.[b]0.0.0.0[/b] [3 Feb 2006 11:22:56] - <unknown> 

¤ WebPager.dll v.[b]0.0.0.0[/b] [7 May 2006 13:00:34] - <unknown> 

¤ xstatus_icons.dll v.[b]0.0.0.0[/b] [18 Jul 2006 2:09:06] - <unknown> 

¤ ymail.dll v.[b]0.0.0.0[/b] [1 Apr 2006 14:28:10] - <unknown> 
    Plugin statically linked to missing module: MSVCP80D.dll
    Plugin statically linked to missing module: MSVCR80D.dll

[b]Protocols and Accounts:[/b]
-------------------------------------------------------------------------------
AIM                      0 - Enabled 2 - Disabled  Loaded
Discord                  1 - Enabled 0 - Disabled  Loaded
GG                       1 - Enabled 0 - Disabled  Loaded
ICQ                      2 - Enabled 0 - Disabled  Loaded
JABBER                   3 - Enabled 0 - Disabled  Loaded
MSN                      1 - Enabled 0 - Disabled  Loaded
SKYPE                    3 - Enabled 0 - Disabled  Loaded
TOX                      0 - Enabled 1 - Disabled  Loaded
WhatsApp                 0 - Enabled 1 - Disabled  Loaded
YAHOO                    1 - Enabled 1 - Disabled  Loaded

[b]Icon Packs:[/b]
-------------------------------------------------------------------------------
 Flags_icons.dll [7 Aug 2021 2:03:50]
 Fp_icons.dll [7 Aug 2021 2:03:50]
 HistoryPP_icons.dll [7 Aug 2021 2:03:50]
 OGSmileys.dll [25 Feb 2003 15:12:58]
 Proto_AIM.dll [2 Dec 2017 13:58:46]
 proto_conn_AIM.dll [4 Dec 2004 13:53:22]
 proto_conn_ICQ.dll [4 Dec 2004 13:53:22]
 proto_conn_Jabber.dll [4 Dec 2004 13:53:22]
 proto_conn_MSN.dll [4 Dec 2004 13:53:22]
 proto_conn_MSN2.dll [4 Dec 2004 13:53:22]
 proto_conn_Weather.dll [4 Dec 2004 13:53:22]
 proto_conn_Yahoo.dll [4 Dec 2004 13:53:22]
 Proto_Discord.dll [7 Aug 2021 2:03:52]
 Proto_Dropbox.dll [2 Dec 2017 13:58:46]
 Proto_Dummy.dll [10 Aug 2021 11:13:18]
 Proto_Facebook.dll [7 Aug 2021 2:03:52]
 Proto_GG.dll [7 Aug 2021 2:03:50]
 Proto_ICQ.dll [10 Aug 2021 11:13:20]
 Proto_IRC.dll [7 Aug 2021 2:03:50]
 Proto_Jabber.dll [7 Aug 2021 2:03:50]
 Proto_MetaContacts.dll [10 Aug 2021 11:13:18]
 Proto_MRA.dll [10 Aug 2021 11:13:20]
 Proto_MSN.dll [24 Feb 2020 19:23:18]
 Proto_Omegle.dll [7 Aug 2021 2:03:50]
 Proto_Sametime.dll [7 Aug 2021 2:03:50]
 Proto_Skype.dll [7 Aug 2021 2:03:50]
 Proto_Steam.dll [7 Aug 2021 2:03:50]
 Proto_Tlen.dll [2 Dec 2017 13:58:46]
 Proto_Tox.dll [7 Aug 2021 2:03:50]
 Proto_Weather.dll [7 Aug 2021 2:03:50]
 Proto_WhatsApp.dll [2 Dec 2017 13:58:46]
 Proto_Yahoo.dll [27 Sep 2016 16:43:08]
 Proto_YAMN.dll [7 Aug 2021 2:03:50]
 SecureIM_icons.dll [7 Aug 2021 2:03:50]
 TabSRMM_icons.dll [6 Apr 2021 20:46:10]
 Toolbar_icons.dll [6 Apr 2021 20:46:08]
 UInfoEx_icons.dll [7 Aug 2021 2:03:50]
 xStatus_Jabber.dll [7 Aug 2021 2:03:50]
 xStatus_MRA.dll [10 Oct 2018 13:51:44]
[/quote][/spoiler]

**Comment by dartraiden** [comment] 2021-08-11 10:48
Duplicate of https://github.com/miranda-ng/miranda-ng/issues/2946

**Closed by dartraiden** 2021-08-11 10:48 UTC
