### ISSUE TITLE
[Database] Due to multiple catastrophical failures and data losses and profile pains, consider a different DB driver

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#1597] opened 2018-09-22 11:26 UTC
**Is your feature request related to a problem? Please describe.**
As seen here:
https://forum.miranda-ng.org/index.php?topic=5547.0
and here
https://forum.miranda-ng.org/index.php?topic=5515.0
and here
https://forum.miranda-ng.org/index.php?topic=5525.0
and here
https://forum.miranda-ng.org/index.php?topic=5488.0
and here
https://forum.miranda-ng.org/index.php?topic=5510.0
and maybe others,
the currently chosen database, mdbx, is not good for the purposes of miranda. In my opinion it is not ready for miranda alpha, let alone to be in miranda main DB. 

**People have their "lives" stored in miranda. It is not acceptable to lose this data and offer no means of recovery for it when the loss occurs.**

**Describe the solution you'd like**
Go back to mmap - or choose a verified, time-tested database like sqlite. Yes it won't be as fast perhaps, but if I have to choose between slow data and potentially losing all data, I choose slow data. Mdbx is already almost 2x bigger than mmap so it doesn't really matter if the new DB would be bigger or whatever. I'm honestly leaning towards SQLite because it's such a common format...

**Describe alternatives you've considered**
There is no alternative client to miranda, and since some updates are required for protocols such as Tox and Discord, it is not possible to run a version of miranda which doesn't utilize mdbx.

**Additional context**
Please reconsider this mdbx experiment. It has caused so many issues to many people, that I don't even know how many of the few that still use this client were put off by this. I love miranda and I've put a lot of effort (and money!) into making sure it survives; but this is starting to be too much. I cannot trust it this way, and the backup management itself is broken too. The only good thing about current miranda is the json import which is excellent and frankly without it I couldn't use miranda at all.

I'm willing to offer some bounty for this, despite the fact it would be money to undo the damage that I didn't cause.

**Comment by aunsane** [comment] 2018-09-22 20:12
I started working with the sqlite driver about 3 weeks ago, but since I do not have time, the development is slow. I can not guarantee that I will finish this project, but I will try to provide basic functionality.

**Comment by LittleVulpix** [comment] 2018-09-22 20:36
Thank you. If time is scarce, would a bounty help allocating some more  towards this goal? I'm sick and tired of mdbx which I'm not saying is anyone's fault, but I also don't feel like I can trust it with my 10+ years of miranda history anymore..

**Comment by AnrDaemon** [comment] 2018-09-22 22:02
Last time we've discussed this, SQLite was said to be too slow for Miranda needs.
But I should agree that MDBX is a catastrofic failure. It is not compatible with itself even, defeating the very reason to use Miranda - its portability.

**Comment by georgehazan** [comment] 2018-09-24 09:09
@AnrDaemon yes, it is slow, for example h++ will open a history of 140K events in ~25 secs.
it either needs some API changes to avoid one-by-one record reading, or to be used on small profiles only

**Comment by georgehazan** [comment] 2018-09-24 09:12
@LittleVulpix 
> Go back to mmap - or choose a verified, time-tested database like sqlite. Yes it won't be as fast perhaps, but if I have to choose between slow data and potentially losing all data, I choose slow data. 

mmap is not functional enough to be the database driver at all, sqlite is VERY slow, about 20 times slower than a key/value database. I've made a deep search among all key/value databases, and libmdbx is the only acceptable solution for now.

**Comment by AnrDaemon** [comment] 2018-09-24 22:32
Until 32- and 64-bit MDBX formats became compatible, it's not an acceptable solution.
SQLite is slow within Miranda database API constraints.
MMAP works just fine, except rarely used edge cases.
I think it's easier to fix (augment) MMAP, than to keep pushing broken MDBX. Creating search indices on the fly is fairly easy.

**Comment by dartraiden** [comment] 2018-09-26 07:35
>> Until 32- and 64-bit MDBX formats became compatible, it's not an acceptable solution.

0.2.0 2018-09-25
Identical database format for 32- and 64-bit builds.

**Comment by LittleVulpix** [comment] 2018-10-06 13:58
@aunsane If you get this sqlite plugin to a usable state, $200 is yours. Every extra second I spend with mdbx, my faith in humanity decreases.

What if the devs had a talk and made sqlite the miranda db of choice and fixed up miranda access to work with that, instead of stupid mdbx that keeps corrupting my db and losing my settings? The corruptions cost me about 3-4hrs a week due to worries about backups, having to store and compress those, and then also time spent actually recovering.

And that's if you're lucky and the backup works; if not you gotta do with jsons. Jsons are literally the only reason I still have my data right now.

**Comment by dartraiden** [comment] 2018-10-08 13:33
https://github.com/miranda-ng/miranda-ng/commit/32197e8186bf0b15555d0910a89709f2fa956919

so we can close this ticket

**Closed by dartraiden** 2018-10-08 13:33 UTC

**Comment by LittleVulpix** [comment] 2019-02-07 18:28
@dartraiden There is currently (and has always been) a bug with SQLite DB whereby it deletes events with same timestamp (sort of like if you had checking for duplicates enabled). I cannot use the DB because of this. I will open another case for it.

**Comment by leo-yuriev** [comment] 2019-08-28 10:43
As the main [libmdbx](https://github.com/leo-yuriev/libmdbx) developer I would like to comment:
1. The cause of an above described problems (most likely) was the [inherited bug in libmdbx](https://github.com/leo-yuriev/libmdbx/issues/38), and at end of september 2018 corresponded fix was [imported](https://github.com/miranda-ng/miranda-ng/commit/97a52219651508b12c40427d01fcfbd9ab206df0) into Miranda-NG source code.
2. **libmdbx was used incorrectly inside Miranda-NG**, at least until [19 February 2019](https://github.com/miranda-ng/miranda-ng/commit/a79f25d3146f1c706c2908310bb348f8e9c127de#diff-dca6c034d75b3263f040030aa51c8fc6). Unfortunately, I can't be sure libmdbx used correctly now, since it is quite a broad subject.
MDBX provides features that need to be optimally used - this is very important for both performance and database size.
3. Source code libmdbx inside Miranda-NG different from the original (isn't a git submodule or git subtree). Therefore, it is difficult for me to give any guarantees:
    - diff with stable/0.2 branch of libmdbx: 33 files changed, 512 insertions(+), 1474 deletions(-)
    - diff with master branch of libmdbx: 38 files changed, 2486 insertions(+), 1393 deletions(-)
    - [The pull-request to fix this](https://github.com/miranda-ng/miranda-ng/pull/2036).

However, I want to thank both the developers of Miranda-NG (especially @ghazan) and everyone who took part in the testing. In General, this allowed to implement an exclusive mode of working with the database on network drives and significantly advance in testing on the Windows platform.

---

I hope that libmdbx will be correctly incorporated into the build of Miranda-NG and the mdbx-driver will properly use the API libmdbx. I am ready to provide all possible assistance in this.

**Comment by LittleVulpix** [comment] 2019-08-28 11:14
@leo-yuriev

I wanted to say thanks for the posts here as well as on the miranda forums. Much appreciated. I am looking forward to the changes that should be possible when @ghazan gets some time to look into it.

I am just praying and hoping that all and any of these changes will never lead to a situation where all user data is lost again (as it has happened too many times).

I understand what you are saying and that it's not inherently libmdbx's fault (rather, it is the strange way miranda has been using the library in combination with an inherited bug), but even so.

Are you going to be more involved in Miranda development (well, as far as libmdbx is involved?). Either way, thanks!

**Comment by juanriccio** [comment] 2019-09-11 16:27
@leo-yuriev
Not a technical remark, but a much deserved offer of praise.

Thanks from me too! Miranda has caused me considerable pain with data losses that hurt. I am rooting for your efforts (and @georgehazan's help!) to give us a functional, modern, rock-solid database driver.

**Comment by rikimo** [comment] 2019-09-11 16:31
@leo-yuriev
Not a technical remark, but a much deserved offer of praise.

Thanks from me too! Miranda has caused me considerable pain with data losses that hurt. I am rooting for your efforts (and @georgehazan's help!) to give us a functional, modern, rock-solid database driver.

**Comment by leo-yuriev** [comment] 2019-09-11 17:35
@rikimo, @georgehazan in this context (probably) it is reasonable to announce some changes of libmdbx in the next 1-2 weeks:
1. Amalgamation source code and build with CMake (mostly done, but more testing required). In other words, libmdbx will be easier to build into another project in the right way and harder to do it wrong (like in miranda currently).
2. The API description will be significantly expanded/refined.
3. Several features will be added to the API to facilitate "lazy" sync to the disk via polling.
This may be very handy to implement one of the properly variants of mdbx-driver as described [here](http://forum.ru-board.com/topic.cgi?forum=5&topic=50156&start=417&limit=1&m=1#1) (in russian).

Some of these improvements are already available in the [devel](https://github.com/leo-yuriev/libmdbx/tree/devel) branch. 

The "Next" version of MDBX will be released as MithrilDB separately from libmdbx. On the other hand, libmdbx will be polished and frozen shortly (except for the bug fixes, of course).
