### ISSUE TITLE
Font colour issue

### ISSUE THREAD

**Issue by thany** [miranda-ng/miranda-ng#2196] opened 2020-02-03 18:17 UTC
This is how I see the about window:

![Capture](https://user-images.githubusercontent.com/152227/73678796-66741880-46b9-11ea-889c-d7ddbddf0751.PNG)

If you're taking the title backgroud, you should take the title foreground colour as well, basically. If my title bar colour was black, I would not be able to see what that says at all, and it's already hard to read as it is.

Might be wise to give the program a check over. Perhaps there are other places where the background and foreground colours are not taken from the same "element".

**Comment by dartraiden** [comment] 2020-02-03 18:24
Duplicate of https://github.com/miranda-ng/miranda-ng/issues/1804

**Closed by dartraiden** 2020-02-03 18:24 UTC

**Comment by georgehazan** [comment] 2020-02-03 18:26
@thany you can subscribe to #1804 to track changes about this problem
