### ISSUE TITLE
Core: crash on reconnection on "netlib.cpp: NetlibCloseHandle"

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#456] opened 2016-10-21 20:01 UTC
**Reported by Corak on 21 Sep 2015 01:13 UTC**

```
Exception: Access Violation at address 7C9113F7. Writing to address 3A043E04.

Stack Trace:
---------------------------------------------------------------
7C9113F7 (ntdll 7C900000): (filename not available) (0): RtlDeleteCriticalSection
120C38C5 (mir_app 120A0000): e:\sources\miranda_ng_compilation\src\mir_app\src\netlib.cpp (309): NetlibCloseHandle
120C2FA4 (mir_app 120A0000): e:\sources\miranda_ng_compilation\src\mir_app\src\netlibhttp.cpp (912): NetlibHttpTransaction
1224E63C (mir_core 12240000): e:\sources\miranda_ng_compilation\src\mir_core\src\modules.cpp (445): FindServiceByName
00BE1F30 ((module-name not available) 00000000): (filename not available) (0): (function-name not available)
1075FF51 ((module-name not available) 00000000): (filename not available) (0): (function-name not available)

```

**Comment by dartraiden** [comment] 2016-12-13 15:59
Duplicate of #441

**Closed by dartraiden** 2016-12-13 15:59 UTC
Labels: bug, core, major
