### ISSUE TITLE
WhatsApp: no text messages receiving from android / ios apps - crypted messages (axolotl encryption support).

### ISSUE THREAD

**Issue by georgehazan** [miranda-ng/miranda-ng#455] opened 2016-10-21 20:00 UTC
**Reported by Corak on 20 Sep 2015 17:55 UTC**
WhatsApp protocol on miranda is not receiving right messages if sent from Android or iOS apps - they are sent as example in netlog:

```
[0B58](20:45:48) [XML received
<message from="972547562463@s.whatsapp.net" id="wH5bpH1UjR9w1" notify="Vadim Dashevsky" of
fline="3" t="1442770518" type="text">
<enc type="pkmsg" v="1">
3!k@    NNPi>T3L}\(xz!FbeQEc/[JGJj(r"R3
!B~G khw76f|

```

And I got such warnings:

```
[20:36:20 0B58](WhatsApp_1]) [XML received
<iq from="g.us" id="iq_1" type="error">
<error code="501" text="feature-not-implemented">
</error>
</iq> 

```

```
[20:45:48 0B58](WhatsApp_1]) [XML received
<ib from="s.whatsapp.net">
<offline count="3">
</offline>
</ib>

[20:45:48 0B58](WhatsApp_1]) [Warning: Node parsing not handled:
<ib from="s.whatsapp.net">
<offline count="3">
</offline>
</ib>

[20:54:17 0B58](WhatsApp_1]) [WhatsApp_1] >> WAConnection: error node iq_1: code = 501

```

Full netlog on WhatsApp

**Comment by georgehazan** [comment] 2016-10-21 20:00
**Modified by Corak on 20 Sep 2015 17:58 UTC**

**Comment by dartraiden** [comment] 2016-12-13 15:58
Duplicate of #440

**Closed by dartraiden** 2016-12-13 15:58 UTC
Labels: bug, critical, WhatsApp
