### ISSUE TITLE
Miranda-NG chrashes when exporting large chat history

### ISSUE THREAD

**Issue by winman3000** [miranda-ng/miranda-ng#1543] opened 2018-08-09 21:45 UTC
With HistoryPP and latest nightly build of Miranda-NG, if I try to Export a very big Chat history, miranda crashes. I have written more than 3 years with this Person.

### Steps to reproduce

1. Be sure that you have installed HistoryPP.
2. Go to a chat with very big data.
3. Press ALT+H or click "History".
4. Try to select all by pressing CTRL+A

Result: Miranda crashes without an error.

**Comment by dartraiden** [comment] 2018-08-09 21:48
Can you enable "Show events count in menu" option (Settings → History) and check number of events (in the contact menu)?

**Comment by winman3000** [comment] 2018-08-09 21:59
There are 85477 events.

**Comment by georgehazan** [comment] 2018-08-10 17:41
that's a known limitation. stupid pascal lists cannot contain more than 64K elements

**Comment by winman3000** [comment] 2018-08-10 17:56
Are there oterh possibilities to export all the data to a file?

**Comment by georgehazan** [comment] 2018-08-10 19:01
in fact you don't have to mark the whole history, just click on a history button and choose the needed Export... menu item, it will export the whole history, as you wish

**Comment by winman3000** [comment] 2018-08-10 20:53
Can you please decribe how to export the whole chat without selecting it? I’m a screen reader user and I’m using historypp.

**Comment by winman3000** [comment] 2018-08-15 15:36
I need a solution to export my whole conversation to Text File like HTML, TXT, RTF etc.

**Comment by georgehazan** [comment] 2018-08-15 15:38
@winman3000 what about Msg_Export plugin?

**Comment by RathaWynter** [comment] 2018-08-15 16:03
@georgehazan I always use mContacts and HTML when i need to delete/move a contact's history to a different protocol. HTML just for backup / readability purposes, but may have to rethink that for the future now that i know theres a bit of an issue with large HTML exports essentially being difficult to load in browser. Will need to see how things develop from here. I was mostly just responding to winman3000 because they seemed to need the help as they indicated they were a blind user, so I was providing some assistance based on what i could figure out.

**Comment by winman3000** [comment] 2018-08-15 16:14
@RathaWynter: thanks a lot, it seams it works for me. Yes the files are big and are very slow to read.

**Comment by LittleVulpix** [comment] 2018-08-16 20:39
Duplicate of https://github.com/miranda-ng/miranda-ng/issues/689 , can probably be closed.

To export entire history, you do not need to select it, simply follow the instructions provided by @RathaWynter

**Closed** 2018-08-30 13:31 UTC
Labels: History++, bug, crash
