### ISSUE TITLE
Steam: Invisible status

### ISSUE THREAD

**Issue by RozekPoland** [miranda-ng/miranda-ng#2665] opened 2020-12-31 08:08 UTC
Currently Steam protocol lacks of _Invisible_ status. Would it be possible to introduce _Invisible_ status for Steam protocol?

**Comment by LittleVulpix** [comment] 2021-06-05 13:06
Close this as duplicate of https://github.com/miranda-ng/miranda-ng/issues/1579

**Closed** 2021-06-05 17:47 UTC
Labels: Steam, enhancement
