### ISSUE TITLE
[Discord] Several api options no longer work correctly

### ISSUE THREAD

**Issue by LittleVulpix** [miranda-ng/miranda-ng#2223] opened 2020-02-18 12:34 UTC
### Expected behavior
Read message is acknowledged. When you leave a guild, it is correctly exited.

### Actual behavior
Message ack (to mark message as read) does not work, leaving guilds and perhaps some other requests no longer work

### Does it work in stable version?
Nope. Discord changed something.

### Steps to reproduce that behavior
I have shared analysis from my side with @georgehazan , it looks like the api now expects a message payload to contain a json-encoded security token. Inital one is "none" and the response provides the first token, afterwards the api expects you to always use the last token it provided in the response, it changes with each response as well.

Currently all of these just cause error 400 bad request since no payload is specified and "headers only" auth no longer works for them.

This is not the case for typing notification which still works without any payload.

**Comment by georgehazan** [comment] 2020-02-18 12:39
duplicate of #2182

**Closed by georgehazan** 2020-02-18 12:39 UTC
Labels: bug
