### ISSUE TITLE
Crash on receiving msg in FB group chat

### ISSUE THREAD

**Issue by marki555** [miranda-ng/miranda-ng#799] opened 2017-04-13 13:19 UTC
Last few versions crash occasionally (maybe last week) and the latest version (downloaded today) crashes almost always when receiving a message in Facebok group chat. Miranda displays crash dialog, but message arrives and Miranda is responsive without issues, even writing new message works (until I select Yes/No in the crash dialog).
Crash dumps attached.
```
Likely cause of the crash plugin: Send/Receive Messages

Exception: Access Violation at address 13126920. Reading from address 6ACED295.

Stack Trace:
---------------------------------------------------------------
13126920 (stdmsg 13120000): c:\sources\miranda_ng_compilation\src\core\stdmsg\src\msgdialog.cpp (581): CSrmmWindow::SetStatusData
131234B5 (stdmsg 13120000): c:\sources\miranda_ng_compilation\src\core\stdmsg\src\msgs.cpp (488): SetStatusText
125CA3F0 (mir_core 125C0000): c:\sources\miranda_ng_compilation\src\mir_core\src\modules.cpp (543): CallService
14CEDFC3 (Facebook 14CE0000): c:\sources\miranda_ng_compilation\protocols\facebookrm\src\proto.cpp (1156): FacebookProto::MessageRead
14D03977 (Facebook 14CE0000): c:\sources\miranda_ng_compilation\protocols\facebookrm\src\communication.cpp (372): facebook_client::insert_reader
14CFA6B7 (Facebook 14CE0000): c:\sources\miranda_ng_compilation\protocols\facebookrm\src\json.cpp (561): facebook_json_parser::parse_messages
14CF5D9C (Facebook 14CE0000): c:\sources\miranda_ng_compilation\protocols\facebookrm\src\process.cpp (977): FacebookProto::ProcessMessages
125C7F27 (mir_core 125C0000): c:\sources\miranda_ng_compilation\src\mir_core\src\threads.cpp (159): forkthreadex_r
747A62C4 (KERNEL32 74790000): (filename not available) (0): BaseThreadInitThunk
77CF0FD9 (ntdll 77C90000): (filename not available) (0): RtlSubscribeWnfStateChangeNotification
77CF0FA4 (ntdll 77C90000): (filename not available) (0): RtlSubscribeWnfStateChangeNotification
125C7EFE (mir_core 125C0000): c:\sources\miranda_ng_compilation\src\mir_core\src\threads.cpp (284): Thread_Wait
07EEFD94 ((module-name not available) 00000000): (filename not available) (0): (function-name not available)
```

[crash-dumps.zip](https://github.com/miranda-ng/miranda-ng/files/919642/crash-dumps.zip)

**Comment by georgehazan** [comment] 2017-04-13 13:31
do you use tabbed interface? or single window?

**Comment by marki555** [comment] 2017-04-13 13:46
single windows

**Comment by georgehazan** [comment] 2017-04-13 15:50
the problem is that the crash point is in the private chat window, not in a group chat
dunno how groupchats can affect single chat rooms

**Comment by Robyer** [comment] 2017-04-13 17:20
@georgehazan I expect FB is automatically reconnected after hibernation, and it joins the groupchats - which usually open chat window immediately. And it looks like it tries to set "message was read..." in statusbar and it crashes for some reason. So that explains why the crash is in groupchat window.

**Comment by georgehazan** [comment] 2017-04-13 17:49
@Robyer in the bug description there's nothing about hibernation. the only strange thing I can see in this crash log is that SetStatusData is executed in the Facebook worker thread

**Comment by marki555** [comment] 2017-04-13 21:10
The crash happens also when the only open window is the group chat (I'm not sure if that was the case in the uploaded crash logs). Right now it crashes in about 50% time when a message is received in group chat. Yes, usually the group chat window opens automatically, but it seems in last few versions it does not... maybe it has something to do with bug which prevents the group chat window to flash (https://github.com/miranda-ng/miranda-ng/issues/797)?
Upon reconnect and opening the group chat window, few old messages get reloaded together with status notify tooltips.

**Comment by Robyer** [comment] 2017-04-14 05:49
@georgehazan Sorry, I thought I opened #798 

Now, about your comment:
>the problem is that the crash point is in the private chat window, not in a group chat
dunno how groupchats can affect single chat rooms

FB calls MS_MSG_SETSTATUSTEXT service with hContact which is definitely group chat contact (see [1]),
which then goes into StdMsg processing (see [2]).

Now I don't know how is merged the StdMsg and StdChat together or how that service internally works, but perhaps `HWND hwnd = Srmm_FindWindow(wParam);` in StdMsg returns wrong window/tab?

[1] https://github.com/miranda-ng/miranda-ng/blob/master/protocols/FacebookRM/src/proto.cpp#L1155
[2] https://github.com/miranda-ng/miranda-ng/blob/master/src/core/stdmsg/src/msgs.cpp#L487

> Right now it crashes in about 50% time when a message is received in group chat. 
It crashes when someone else reads the message on FB, that explains only the 50% chance of crash.

**Comment by marki555** [comment] 2017-04-18 10:57
Today (with latest Miranda NG) I could receive several messages with the group chat window closed, showing only popup notifications. However it crashed when I tried to open the group chat window with unread messages. The crash log looks little different, so I am attaching it here.
[2017.04.18.zip](https://github.com/miranda-ng/miranda-ng/files/928823/2017.04.18.zip)

**Comment by marki555** [comment] 2017-04-20 08:32
@georgehazan / @Robyer, do you need any troubleshooting from me?

**Comment by fuuzi** [comment] 2017-04-26 10:50
same here... I can send crash dumps from last month, if you need

**Comment by marki555** [comment] 2017-04-30 10:49
@georgehazan Any idea where the bug could be?
If not, what about adding an option to menu to disable handling of these reading notifications? Because now Miranda is unusable for Facebook with anyone having active group chat.

**Comment by Robyer** [comment] 2017-05-02 06:59
Meanwhile you can use Scriver or TabSRMM (at least in TabSRMM it should work correctly I believe) instead of StdMsg. I will add some option to temporarily disable it later...

**Comment by marki555** [comment] 2017-05-02 13:46
Thanks, with TabSRMM it works without crashing (I just need to customize/skin it so that it looks the same as before).

**Comment by Robyer** [comment] 2017-05-05 21:52
Hidden option added. Add byte key "NoChatMessageReadNotify" with value 1 to use it. Then it should work in StdMsg without crashes.

**Closed** 2017-08-15 10:49 UTC
Labels: crash, Facebook, regression, StdMsg
