### ISSUE TITLE
IRC chat doesn't open

### ISSUE THREAD

**Issue by don-reba** [miranda-ng/miranda-ng#867] opened 2017-07-20 14:07 UTC
This actually started at least half a year ago, but I "fixed" it by rolling back to the stable version. I was hoping the problem would be solved in the meanwhile, but it wasn't.

I double-click on an IRC channel in my contact list or select _Open Chat Window_ in its menu and expect the chat window to open, but nothing happens. I usually use Scriver, but it's the same with TabSRMM.

Version info: http://vi.miranda-ng.org/detail/DonReba

**Comment by LittleVulpix** [comment] 2017-07-20 16:58
This works fine for me on the latest dev version with tabsrmm. You said "it's the same with tabsrmm", could you try it again and post the VI _with_ tabsrmm and latest dev build?

**Comment by Robyer** [comment] 2017-07-20 17:13
You can also try to open Options / Customize / Menus and click Reset (but you will lost your menus settings - but it might fix the issue).

**Comment by dartraiden** [comment] 2017-07-20 17:14
What about other chats? (Jabber conferences, etc.)

**Comment by don-reba** [comment] 2017-07-20 17:19
@LittleVulpix Done. Updated the version info.

@Robyer Won't that just reset the menus?

@dartraiden Good call. Jabber works with both Scriver and TabSRMM. It's only IRC that doesn't.

**Comment by LittleVulpix** [comment] 2017-07-20 17:43
@don-reba this happens to me if I'm not connected to the network. You cannot open a chat if you are not connected. It might also be possible you are connected to a different server, I recall there was something strange that caused IRC settings to change, some builds back. Can you verify that you are connected to IRC, and furthermore that you are connected to the right server, when the issue occurs?

**Comment by don-reba** [comment] 2017-07-20 17:51
100% sure I'm connected. The channel is shown as online in the contact list, and I see myself entering it in the online log. Clicking it opens up the chat in the stable version, but not in the development one.

**Comment by georgehazan** [comment] 2017-07-20 18:42
I need a network log
http://wiki.miranda-ng.org/index.php?title=Network_log

**Comment by don-reba** [comment] 2017-07-20 18:50
Clicking the channel does not log any network activity.

**Comment by LittleVulpix** [comment] 2017-07-20 19:00
That's weird.. it should, if you're joining it after all.

**Comment by don-reba** [comment] 2017-07-20 19:02
I auto-join. Clicking should just open the chat window.

**Comment by georgehazan** [comment] 2017-07-20 19:31
@don-reba that's a problem of menu upgrade... you need to go to Options - Customize - Menus and reenable the menu item 'Join chat'. Dunno how it got disabled in your case

**Comment by don-reba** [comment] 2017-07-20 20:04
The _Join chat_ command is there for chats that I have not already joined. For chats that I have joined, the command is _Open chat window_. Neither of them actually opens a window.

**Comment by don-reba** [comment] 2017-07-20 20:06
The server window still works, by the way.

**Comment by georgehazan** [comment] 2017-07-20 20:22
yes, and this command must be enabled
![image](https://user-images.githubusercontent.com/4628541/28437153-4a422460-6da2-11e7-9841-29fbac05922b.png)

**Comment by don-reba** [comment] 2017-07-20 21:01
It is.
![Menus](http://i.imgur.com/HsyjWVI.png)

**Comment by Robyer** [comment] 2017-08-16 08:37
@don-reba Can you backup your profile, then try to Reset the menus and check if at least that fixes it? Then you can compare the menus settings via DbEditor and see what differs.

**Comment by don-reba** [comment] 2017-08-25 18:50
@Robyer I tried it. Doesn't help. And now IRC is broken in the release version. :(

**Comment by LittleVulpix** [comment] 2017-08-25 18:59
That is very odd. It works for me (and has always worked for me).

Does it happen to you with a completely clean profile? (just using your plugins for example, but a brand new miranda installation in a different folder).

**Comment by don-reba** [comment] 2017-08-25 19:11
I'm not sure I'll have time to test it before next week. I'm surprised "menu settings" were the only hypothesis put forward. I wouldn't expect there to be that much code on the path between clicking a menu entry to open an IRC window and the window opening. Especially considering that it works for IRC server windows and Jabber.

**Comment by f2d** [comment] 2017-09-04 10:42
Had the same thing with one IRC channel (inherited from old Miranda IM user profile into newly installed NG v0.95.6 18465 x64). I could create and join any other new channel and it opened/reopened a tab/window with whatever method, except that old one. It opened if I left and rejoined using a server window command, but after closing the window, trying to open from contact list did nothing.

I deleted the contact and joined it again, now all seems OK.

**Comment by georgehazan** [comment] 2017-09-04 10:58
@don-reba well.... could you at least make a screenshot of the popup menu that appears on Rclick on this IRC chat in contacts list?

**Comment by don-reba** [comment] 2017-09-04 11:05
@f2d It worked! It never occurred to me to try that.

**Comment by don-reba** [comment] 2017-09-04 11:08
@georgehazan 
![menu](https://i.imgur.com/kbv0O1f.png)

**Comment by georgehazan** [comment] 2017-09-04 14:33
that's after you removed it and added back?

**Comment by don-reba** [comment] 2017-09-04 15:37
It didn't change. I checked.

**Comment by georgehazan** [comment] 2017-09-04 18:33
but after deletion it works again? must be a problem in this contact's settings... is that possible to recreate the problem?

**Comment by f2d** [comment] 2017-09-04 22:33
@georgehazan If i restore backup of old user profile to a copy of NG install, remove all unneeded protocols, plugins and contacts and leave just that one channel in IRC, the problem is back there. Window is not opening, even from server window command joining (probably some global setting was changed after install in the first copy, probably "Message sessions - Group Chats - Do not popup the window when joining" was enabled before and still in the backup).

**Comment by f2d** [comment] 2017-09-04 23:17
I made a repack copy as clean as I could, removed all /join commands at startup, and the first manual join (by clicking it in contact list) opens the channel, but not reopen after window is closed.
Server window command is not relevant, it seems.

I'm attaching this copy if you want to test. The channel is almost empty and has nothing sensitive.
[ng0.95.6_old_profile_test,#z_wont_reopen_window_until_its_contact_is_deleted.7z.zip](https://github.com/miranda-ng/miranda-ng/files/1275631/ng0.95.6_old_profile_test.z_wont_reopen_window_until_its_contact_is_deleted.7z.zip)

**Comment by f2d** [comment] 2017-09-04 23:53
I made a repack copy as clean as I could (using DBEditor++ plugin), removed all /join commands at startup, and the first manual join (by clicking it in contact list) opens the channel, but not reopen after window is closed.
Server window command is not relevant, it seems.

I'm attaching this copy if you want to test. It reproduces the subject bug for me.
[ng0.95.6_old_profile_test,#z_wont_reopen_window_until_its_contact_is_deleted.7z.zip](https://github.com/miranda-ng/miranda-ng/files/1275656/ng0.95.6_old_profile_test.z_wont_reopen_window_until_its_contact_is_deleted.7z.zip)

**Comment by georgehazan** [comment] 2017-09-08 13:41
@f2d congratulations, bug reproduced on tabSRMM :-)

**Comment by georgehazan** [comment] 2017-09-08 13:51
@f2d well, it's simple. inside the profile this chat has name #Z, while at the server it's in lowercase: #z
I wonder how it was added but it simply cannot find this session after creation

**Comment by georgehazan** [comment] 2017-09-08 14:28
aha, got it. previously chat room ids were compared case-insensitively...

**Closed** 2017-09-08 14:30 UTC
Labels: bug, IRC, regression

**Comment by don-reba** [comment] 2017-09-08 14:53
Thanks!

**Comment by rkingett** [comment] 2025-03-17 01:11
I know this is old, but along the same lines, IRC isn't showing up on the add account dialog box, nor is IRC  quick connect dialog box not showing up at all, even on fresh installs. Is there a way to make sure IRC is active even on fresh installs?
